### ISSUE TITLE
Documentation is needed for the config package

### ISSUE THREAD

**Issue by eap** [DataBiosphere/leonardo#102]
I've been trying to get this stood up so we can evaluate it for use at Verily, so far unsuccessfully. I realize it's a work in progress, but being able to get it bootstrapped would help us contribute features and fixes.

Right now there's a grab-bag of config options in the package `org.broadinstitute.dsde.workbench.leonardo.config` that aren't documented. Some options are obvious while others require digging through the source to see what they do.

My opinion is that documenting the config package would be preferable to creating a pristine example config at this point in time since it seems like the config options could still evolve substantially.

**Comment by helgridly** [comment]
I've been meaning to make sure that [reference.conf](https://github.com/DataBiosphere/leonardo/blob/develop/src/main/resources/reference.conf) is configured sensibly and full of examples, and use that as the documentation. That work is likely to officially stay on the back burner for a couple of weeks, but i might be able to poke at it unofficially. In the meantime feel free to ask questions here if you run into anything.
