### ISSUE TITLE
run-mysql.sh requires non-public docker image

### ISSUE THREAD

**Issue by e4p** [DataBiosphere/leonardo#103]
The automation script docker/run-mysql.sh (which is required by docker/build.sh) currently uses the docker image `broadinstitute/dsde-toolbox` for the mysql validation step. This image is non-public (or, possibly, it hasn't been pushed to the Docker registry).

I was able to get the validation step to work by swapping the image for `mysql:$MYSQL_VERSION`. I don't know if this swap breaks expectation of the current validation or pending features. Could be an easy fix neither of these are the case.

**Comment by helgridly** [comment]
I think you're spot on here. I'll put together a quick PR and see if it breaks anything.

**Comment by helgridly** [comment]
fixed by #106
