### ISSUE TITLE
Support multiple Jupyter extensions (UI and server)

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#130]
Original JIRA: https://broadinstitute.atlassian.net/browse/GAWB-2998

Currently in the ClusterRequest we have the field jupyterExtensionUri that installs a single Jupyter UI extension.

We should support multiple extensions, including both client and server extensions as described here:

http://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Distributing%20Jupyter%20Extensions%20as%20Python%20Packages.html

Note that it is possible that a single extension can contain a server extension only, a UI extension only, or both.

Remove our existing extensions (the UI extension to cover Google auth and the server extension to add /localize) from their hardcoded install procedure and use this procedure instead. Allow Leo administrators to specify "default extensions" in config.

You should probably write a tech doc detailing how we'll achieve this. An incomplete list of things to consider:
- How will we get the list of extensions from Leo onto the Docker?
- How will we localize the extensions from GCS onto the Docker image?
- How will we determine which extensions are server, client, or both in order to install them correctly?

**Comment by calbach** [comment]
+1, we will likely need support for server extensions in AoU to add logic around delocalization of notebooks back to GCS. Note: it's conceivable the specific delocalization feature could be provided by Leonardo, but would be nice to have some flexibility to extend this ourselves if needed.

FYI: my current ultra hacky and brittle workaround (for prototyping purposes only) is to use the `jupyterUserScriptUri` to append my own Python code onto `/etc/jupyter/custom/jupyter_localize_extension.py`

**Comment by rtitle** [comment]
Cool - yeah our extension support needs some love. We currently have support for notebook extensions (but probably doesn't work now because of #221, sigh) and 0 support for server extensions.
