### ISSUE TITLE
Auto-shutdown / auto-freeze clusters

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#133]
Original JIRA: https://broadinstitute.atlassian.net/browse/GAWB-2992

If a cluster is running and has not been accessed for X (configurable) amount of time, auto-pause (or auto-kill) it. This will likely require a new monitoring actor in Leo.

Possible definitions of "accessed" include:
- Leo HTTP endpoints hit that relate to the cluster
- Proxy connections, including websockets
- Spark jobs running on the cluster

**Comment by rushtong** [comment]
@rtitle - what is the time it takes to pausing+unpause a cluster?

**Comment by rtitle** [comment]
@rushtong pausing takes around ~1 minute. Resuming is quicker -- I've observed about ~10 seconds. Note also you can start a cluster that is in Stopping state.

**Comment by rushtong** [comment]
@rtitle Thank you!
