### ISSUE TITLE
Leo-created clusters and their associated Jupyters should survive a restart of their GCE VMs

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/leonardo#135]
In GCE you can stop and resume VMs. With a stopped VM you only pay for the attached storage.

For #128 and #131, Leo will need to restart GCE VMs. In such cases they'll get a new IP. This will affect:

* The Leo proxy, which needs to know where to forward Jupyter packets to
* Potentially Spark will need to be told that the workers have now moved -- though if the communication is through hostname this might be free

It's also very likely that starting the Jupydocker needs to happen in a startup script.

Acceptance criteria for this ticket: internal Leo functions for start and stop cluster should exist, and stopping and starting a cluster should work as expected, including preserving any work (e.g. notebook files) that the user created.

**Comment by rtitle** [comment]
I did a quick test of stopping/starting a single-node cluster's VM. The proxy was NOT able reconnected after a restart -- I suspect because the instance IP changed. So that is the first thing to fix.

Still TBD if Spark can handle the restart.
