### ISSUE TITLE
Leo/Sam auth: SamAuthProvider should not delete the cluster resource in Sam

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#137]
Currently `LeoService.internalDeleteCluster()` calls `SamAuthProvider.notifyClusterDeleted()` calls `SwaggerSamClient.deleteNotebookClusterResource()`.  However when a cluster is deleted it is NOT gone yet -- the ClusterMonitorActor needs to monitor its state from Deleting to Deleted, and it should still be retrievable via Leo get/list APIs. Therefore I don't think Leo should call Sam `deleteNotebookClusterResource()` until the `ClusterMonitorActor` confirms deletion.

I found this while using the UI: when I delete a cluster it disappears from the UI immediately, because the "list clusters" endpoint no longer returns it because it is no longer permissioned in Sam (though it is still Deleting in Leo).

**Comment by jmthibault79** [comment]
When Leonardo transitions a cluster from `Deleting` to `Deleted` then we *do* want to call `SwaggerSamClient.deleteNotebookClusterResource()`.

The current PR does not cover this, so I will add it.
