### ISSUE TITLE
Expose error message from Errored clusters

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/leonardo#141]
Broken out from [GAWB-2839](https://broadinstitute.atlassian.net/browse/GAWB-2839).

After #140, a user with an errored cluster will be able to see the staging bucket containing the error logs.

- [ ] Create a new optional field in the Cluster case class for the error message; this will need to be saved to the database
- [ ] Display a link to the error logs

**Comment by vkumra-broad** [comment]
Handover and Tech doc:
https://docs.google.com/document/d/1V3KEupKKvjucYpYX8no4D_cn9Ml3yrDMelGm1nmFLuw/edit#
