### ISSUE TITLE
Move Jupyter Docker image from DockerHub to GCR

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/leonardo#142]
Moved from [GAWB-2467](https://broadinstitute.atlassian.net/browse/GAWB-2467)

The Google Container Registry is a place you can put Docker images that Docker knows how to talk to. Since GCR is within the Googleverse, it's _much_ quicker to pull images from than DockerHub, and will thus significantly decrease time to spin up notebook clusters.

The following links will give you an overview:

https://cloud.google.com/container-registry/docs/quickstart
https://cloud.google.com/container-registry/docs/pushing-and-pulling

Essentially, instead of using
`docker.io/broadinstitute/our_jupyter_stack:tag`
we'd push to and pull from
`us.gcr.io/broad-dsde-dev/our_jupyter_stack:tag`, or something like that.

**Comment by rtitle** [comment]
Tech Doc: https://docs.google.com/document/d/1hBGSW7PKIoNgNxhWO_zUCMoB3eZrC_pe9aqVCuviVMA/edit?usp=sharing

**Comment by rtitle** [comment]
Note: depends on https://github.com/DataBiosphere/leonardo/issues/146
