### ISSUE TITLE
Upgrade to Dataproc 1.2

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/leonardo#144]
[GAWB-3080](https://broadinstitute.atlassian.net/browse/GAWB-3080)

We currently use Dataproc 1.1 which gives us Spark 2.0.2. Dataproc 1.2 gives us Spark 2.2.0. See:
https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-versions

The reason we don't use Dataproc 1.2 is there is no pre-built Hail distribution for Spark 2.2.0. See:
https://hail.is/docs/stable/getting_started.html

In addition to a newer Spark, Dataproc 1.2 also has some config improvements. In particular this issue regarding *spark.yarn.am.memory* was fixed: https://stackoverflow.com/questions/41185599/spark-default-settings-on-dataproc-especially-spark-yarn-am-memory

Option A:
Build Hail against Spark 2.2.0 in the Dockerfile. Ideally this could use a multistage docker build to keep the image size down: https://docs.docker.com/engine/userguide/eng-image/multistage-build/. Although it may still increase the build time.

Option B:
Contact Hail team, see if they will be publishing a version based on Spark 2.2.0 anytime soon.

**Comment by rtitle** [comment]
P4 with the expectation of getting to this in Q4 2018
