### ISSUE TITLE
Leo: Add automation test to test dataproc staging bucket acl

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/leonardo#145]
[GAWB-3047](https://broadinstitute.atlassian.net/browse/GAWB-3047)

Add test to test that the dataproc bucket acl is being set correctly -- google doesn't give ANY service accounts access to it by default. This came out of GAWB-3026 and is being punted till after #146 is done.

**Comment by rtitle** [comment]
Closing this - I believe this is covered in our current automation tests.
