### ISSUE TITLE
Use semantic versioning on api-docs.yaml to communicate changes to consumers

### ISSUE THREAD

**Issue by mtmorgan** [DataBiosphere/leonardo#1495]
As best practice, https://github.com/DataBiosphere/leonardo/blob/6303b8ed59dae70bcbb3262536267acd92c1e73a/http/src/main/resources/swagger/api-docs.yaml#L6 should be incremented (e.g., using semantic versioning) to help communicate changes to clients of this service.

A similar issue applies to terra / firecloud.

**Comment by Qi77Qi** [comment]
Hi @mtmorgan , PRed the change...btw, we don't usually triage github issues...If you create ticket in https://broadworkbench.atlassian.net/secure/RapidBoard.jspa?rapidView=35&projectKey=IA&view=planning.nodetail&issueLimit=100 for non-urgent requests, we triage new tickets weekly
