### ISSUE TITLE
SPIKE: Remove code duplication in unit tests

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/leonardo#150]
[GAWB-3043](https://broadinstitute.atlassian.net/browse/GAWB-3043)

This is pretty minor, but annoying. In Leo unit tests we have the same or similar test data in the following places:

- CommonTestData
- TestLeoRoutes
- LeonardoServiceSpec
- AuthProviderSpec

...and maybe others as well. This makes it hard to refactor code when you have to change test data in 4 places. It would be nice to consolidate all test data into _one_ place (maybe CommonTestData) and have everything just mix in that trait.

**Comment by rtitle** [comment]
https://github.com/DataBiosphere/leonardo/issues/394 is another source of code duplication

**Comment by rtitle** [comment]
This ticket is a spike: review our test code and create a tech doc for sources of code duplication. From that doc, prioritize and fix the issues.

**Comment by kyuksel** [comment]
We have a bunch of
```scala
dbFutureValue { _.clusterQuery.save(c1, Option(gcsPath("gs://bucket1")), Some(serviceAccountKey.id)) } where we may be able to reduce some duplication by factoring out `dbFutureValue { _.clusterQuery.save` part and defaulting the fields to the most commonly used ones.
```

**Comment by rtitle** [comment]
#394 should be a ticket that comes out of this spike. Please create other tickets as necessary.
