### ISSUE TITLE
Make FiaB Leos deploy their corresponding leo-notebooks Jupyter tag

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/leonardo#157]
[GAWB-2916](https://broadinstitute.atlassian.net/browse/GAWB-2916)

If I have a branch of Leo and stand up a new FiaB with BUILD_SERVICES pointing to that branch, it builds the corresponding Docker image for jupyter-notebooks and tags it with my Leo branch name. But the cluster-compose references jupyter-notebooks:$ENV, not the Leo branch name. Fix this so that changes to my jupyter-notebooks docker deploy with the rest of my FiaB Leo.

**Comment by rtitle** [comment]
Happened again for me: https://github.com/DataBiosphere/leonardo/pull/251
