### ISSUE TITLE
Automation tests should execute in parallel

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/leonardo#158]
[GAWB-2953](https://broadinstitute.atlassian.net/browse/GAWB-2953)

ScalaTest is supposed to run individual _tests_ in a suite in parallel if you mix in ParallTestExecution (we do this in ClusterMonitoringSpec) and pass in a Distributor (we don't do this). The last post in the following thread has a hacky solution to expose ScalaTest's package-private ConcurrentDistributor for use in an overriden run() method.
https://github.com/scalatest/scalatest/issues/898

**Comment by aweng98** [comment]
Revamped Leo test suites. `LeoInteractionSpec` was big and was the longest time in terms of execution time. New and small sized suites created, organized by Notebook kernel types. Enabled more JVMs in SBT execution.
