### ISSUE TITLE
Add mozilla/jupyter-spark extension to default installed list

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/leonardo#160]
Alisa requested we install this Jupyter extension which visualises the progress of your Spark jobs: https://github.com/mozilla/jupyter-spark

The extension scrapes the Spark UI to grab the data to render in the notebook. I did a tiny bit of investigation and in Dataproc-land the default Spark port is indeed 4040, but you need to have started a SparkContext -- i.e. a pyspark Jupyter notebook in our cases -- for the Spark UI to show up. I would hope that the extension behaves well in the case where you haven't run your first cell (and therefore have no SparkContext yet), but I haven't checked.

This could possibly be done with a user script, see #126

**Comment by rtitle** [comment]
If this scrapes the Spark UI from the client-side it would necessitate proxying the Spark UI through Leo -- probably best tracked as a separate ticket.

**Comment by rtitle** [comment]
With our improved extension support (including serverside extensions), this might just work out of the box in Leo. Need to try it.
