### ISSUE TITLE
fiab-start should check Leonardo status

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/leonardo#161]
[GAWB-3087](https://broadinstitute.atlassian.net/browse/GAWB-3087)

Leonardo FIAB deployment failure does not cause a Jenkins fiab-start job to fail.  fiab-start checks Orchestration status to confirm services are up, but this doesn't include Leonardo.

Either: change Orchestration /status to include Leonardo, or include a Leonardo /status check in the fiab-start task.

NOTE: Orchestration /status 500 also does not cause a fiab-start to fail.  We should fix that too.  Example: https://fc-jenkins.dsp-techops.broadinstitute.org/view/FIAB/job/fiab-start/4360/console

**Comment by rtitle** [comment]
Orchestration doesn't call Leo in prod, so I'm not sure we should include Leo /status in Orch /status. I am 👍 on adding Leo /status to fiab-start though.

**Comment by rtitle** [comment]
This is done
