### ISSUE TITLE
Verify better-behaved UI

### ISSUE THREAD

**Issue by jmthibault79** [DataBiosphere/leonardo#163]
From https://broadinstitute.atlassian.net/browse/GAWB-2879 and https://broadinstitute.atlassian.net/browse/GAWB-2880

* Setting Auth Cookie
> After I launch a cluster in the Firecloud Notebooks UI, I click on the link to open the Jupyter home page.  Often (always?) I see JSON text indicating I'm not authorized instead of the Jupyter page.  After manually setting my FCToken/FCtoken cookie on the cluster page, I can access it correctly.

This should now be fixed.  Remove explicit cookie-setting from the Integration Tests (CookieAuthedPage) and confirm that everything still works.

* Notebooks Tab
> Sometimes a whitelisted user in a Workspace does not see the Notebooks tab, even though they should.  Force-refreshing can sometimes fix this, and clicking other tabs can sometimes fix this.

> Idle speculation: this problem may be a caching issue.

Confirm that the Notebooks tab reliably appears for all users in the post-whitelist world.

**Comment by rtitle** [comment]
> Remove explicit cookie-setting from the Integration Tests (CookieAuthedPage) and confirm that everything still works.

A cookie still needs to be set _somehow_. We can either do it by:
a) explicitly setting a cookie as we do now in most tests
b) doing the proxy `/setCookie` handshake, as is done by our UIs and 1 auto test ("should do cross domain cookie auth").

Is the ask for this issue to standardize on (b)?

> Confirm that the Notebooks tab reliably appears for all users in the post-whitelist world.
Yes, and we need to write UI-swat for the Notebooks tab in general, we have exactly 0 UI tests verifying Notebooks tab functionality 😱

**Comment by jmthibault79** [comment]
OK - I misunderstood the cookie situation.  For these choices (b) seems closer to the real world.

**Comment by MatthewBemis** [comment]
Closed because we are no longer supporting FireCloud UI
