### ISSUE TITLE
Store deleted-by user in Clusters table and pass that value to authProvider.notifyClusterDeleted()

### ISSUE THREAD

**Issue by jmthibault79** [DataBiosphere/leonardo#167]
I got lazy in #139 and didn't pass the actual user deleting the cluster to the AuthProvider because it wasn't available to the ClusterMonitorActor.  This isn't an immediate concern because the only extant implementation (SamAuthProvider) doesn't use this information, but we should come back to this because it means fulfilling the contract we're making in the interface.

We do know the user deleting the cluster at the time of the API call, so we can store that in the Clusters table.  The ClusterMonitorActor can then query for that information when it needs to call AuthProvider.notifyClusterDeleted()

**Comment by helgridly** [comment]
I also think that keeping a record of both creator and deleter (deletor?) in the db is independently helpful, so 👍 on this
