### ISSUE TITLE
Performance testing for concurrent cluster listing, cluster connection

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/leonardo#168]
It is reasonable to assume that 60 users will wish to simultaneously access Leonardo endpoints. Specifically:
* Listing available clusters
* Connecting to a cluster via the proxy and issuing run-cell commands at a notebook

We should test concurrent calls to these endpoints at 60, 90, and 180 users.

We do not expect (at this time) to have this level of concurrent load on the cluster creation/deletion/etc. endpoints. If metrics reveal problems in these areas after the hosted service goes live, we can add additional performance testing at that time

**Comment by kcibul** [comment]
So happy to see this ticket!
