### ISSUE TITLE
Rename PetsPerProjectServiceAccountProvider / PetServiceAccountProvider

### ISSUE THREAD

**Issue by jmthibault79** [DataBiosphere/leonardo#183]
Suggested in #181 but deferred for expediency.

Rob sez:

I propose we rename these classes to something more sensible. Both of them create pets per project -- the difference is that 1 specifies the pet as a clusterServiceAccount, the other as a notebookServiceAccount. So maybe:

PetsPerProjectServiceAccountProvider -> PetClusterServiceAccountProvider
PetServiceAccountProvider -> PetNotebookServiceAccountProvider

and we would use PetClusterServiceAccountProvider in FireCloud.

Also it'd be nice to have a default ServiceAccountProvider impl that we could put in the example config. Maybe while we're at it we could add a DefaultServiceAccountProvider which returns None for everything (thus using the Compute Engine default service account for creating the cluster, no pets at all).

**Comment by rtitle** [comment]
Done in https://github.com/DataBiosphere/leonardo/pull/182
