### ISSUE TITLE
Add Hail 0.2, which has support for Python 3

### ISSUE THREAD

**Issue by ansingh7115** [DataBiosphere/leonardo#193]
Currently, Hail 0.1 supports only Python 2, meaning notebooks that are running on the Python 3 kernel cannot use Hail. A beta version of Hail 0.2 is coming out (late February, early March) that supports only Python 3. 

Once Hale 0.2 comes out, we should install both versions so that both our Python kernels can use it. (we should explore if this is even possible)

There should be an announcement when Hail 0.2 is released, but slack Timothy Poterba (on the Hail team) for further details. He's very nice so he's also a great resource when doing this ticket.

**Comment by rtitle** [comment]
Related: https://github.com/DataBiosphere/leonardo/issues/144

We should also find out what version of Spark Hail 0.2 supports/requires.

**Comment by ansingh7115** [comment]
Timothy Poterba says "should work with 2.0.2, 2.1.0, 2.2.0"

**Comment by rtitle** [comment]
P4 with the expectation of getting to this in Q4 2018
