### ISSUE TITLE
UI - cluster list partially covered by horizontal scroll bar

### ISSUE THREAD

**Issue by ahaessly** [DataBiosphere/leonardo#194]
The horizontal scrollbar on the notebooks page covers part of the last cluster in the list![Screen Shot 2018-02-13 at 3.17.31 PM.png](https://images.zenhubusercontent.com/5a6bab7b4b5806bc2bc47bad/c2a0ab2b-9775-4af2-b4b7-09edff6111fd)

**Comment by MatthewBemis** [comment]
Closed because we are no longer supporting this UI
