### ISSUE TITLE
Unwhitelist FireCloud UI

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#198]
Acceptance criteria: 
- FireCloud always displays the notebooks tab and does not call Leo /isWhitelisted
- Leo /isWhitelisted endpoint is removed

**Comment by rtitle** [comment]
Depends on #199 and #200

**Comment by rtitle** [comment]
Include: add UI-automation test for the create cluster/delete cluster cycle. No notebook interaction test cases.

**Comment by ansingh7115** [comment]
Main PR for this ticket: https://github.com/broadinstitute/firecloud-ui/pull/1214
