### ISSUE TITLE
FireCloud UI tweaks for notebooks beta

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#199]
1. Add a beta banner to Notebooks tab
   - Q: any other examples of this in the UI? Consult with a UI designer.

2. Add a link to notebooks documentation in the Notebooks tab:
   - Placeholder URL for now: https://software.broadinstitute.org/firecloud/documentation/quickstart?page=notebooks

**Comment by ansingh7115** [comment]
Clusters endpoint is taking forever to return - we should either make that faster or show a spinner while we wait

**Comment by rtitle** [comment]
+1 on a spinner. It's probably due to calling Sam for each active cluster. We cache Sam results but the first call will still be slow.
