### ISSUE TITLE
Run a script periodically that deletes orphaned DataProc clusters

### ISSUE THREAD

**Issue by jmthibault79** [DataBiosphere/leonardo#207]
It's easy to abandon a cluster by e.g. closing a FIAB.  They can be expensive!  Let's purge the dev/test environments on a regular basis, maybe weekly.

Bonus points for making this generic to help chase down other resources like projects and buckets.

**Comment by helgridly** [comment]
Give or take:

```
gcloud auth some_admin@test.firecloud.org
for x in gcloud projects list:
  for cl in gcloud dataproc clusters list --project x:
    gcloud dataproc clusters delete cl
```

**Comment by jmthibault79** [comment]
Script is at https://github.com/broadinstitute/firecloud-tools/pull/25
