### ISSUE TITLE
Cluster create ended with error when using value "n1-highcpu-4" for option MasterMachineType

### ISSUE THREAD

**Issue by aweng98** [DataBiosphere/leonardo#208]
In "Create Cluster" modal window,, I selected value "n1-highcpu-4" for options "Master Machine Type" and "Worker Machine Type". Cluster creation failed two times in a row.

Create cluster works find when I used default value "n1-standard-4" for above two options.

**Comment by aweng98** [comment]
https://firecloud-fiab.dsde-dev.broadinstitute.org:30443/api/clusters?includeDeleted=false

{
    "stagingBucket": "aw-cluster-feb20-2-staging-f88aa842-3e67-4b6b-9816-3d92ff0df5e8",
    "machineConfig": {
      "numberOfWorkers": 0,
      "masterMachineType": "n1-highcpu-4",
      "masterDiskSize": 500
    },
    "creator": "ron.weasley@test.firecloud.org",
    "googleProject": "broad-dsde-dev",
    "labels": {
      "clusterServiceAccount": "pet-114763077412354570085@broad-dsde-dev.iam.gserviceaccount.com",
      "clusterName": "aw-cluster-feb20-2",
      "creator": "ron.weasley@test.firecloud.org",
      "googleProject": "broad-dsde-dev"
    },
    "status": "Error",
    "clusterUrl": "https://leonardo.dsde-dev.broadinstitute.org/notebooks/broad-dsde-dev/aw-cluster-feb20-2",
    "clusterName": "aw-cluster-feb20-2",
    "operationName": "projects/broad-dsde-dev/regions/us-central1/operations/bb0c0ce6-5d07-4e2a-bd38-195823cc291d",
    "serviceAccountInfo": {
      "clusterServiceAccount": "pet-114763077412354570085@broad-dsde-dev.iam.gserviceaccount.com"
    },
    "googleId": "52b4b6b6-f92f-4289-8a86-d8da1ecf31be",
    "createdDate": "2018-02-20T21:31:49.448Z"
  }

**Comment by rtitle** [comment]
Google machine type reference: https://cloud.google.com/compute/docs/machine-types

**Comment by ansingh7115** [comment]
I am unable to reproduce this - tried creating a couple clusters on dev with machine type "n1-highcpu-4" but they seemed to work. I'm wondering if these were a result of some transient Google issue?
