### ISSUE TITLE
Trim Jupyter Docker images

### ISSUE THREAD

**Issue by jmthibault79** [DataBiosphere/leonardo#216]
Notebook Docker images are currently over 2GB.  Let's make it smaller.

Suggestions:
* use a different base image
* use fewer layers
* clean up caches and the ends of layer commands

**Comment by rtitle** [comment]
* look into multistage builds

**Comment by rtitle** [comment]
Also investigate the R install - it builds a lot of stuff from source and may leave around intermediate files.
