### ISSUE TITLE
Leo SA should not need permissions on user scripts

### ISSUE THREAD

**Issue by ansingh7115** [DataBiosphere/leonardo#220]
Currently, when a user specifies a script, the Leonardo service account is required to have storage.objects.get access on that object for it to run (or for the script to be public). This should not be necessary. As long as the user as access to the object, leo should be able to get the script.

This may be related to a "get" call leo does using the Leo SA to check if the bucket exists in the first place.

**Comment by rtitle** [comment]
Here is the bucket "get" call Leo is making as the Leo service account:

https://github.com/DataBiosphere/leonardo/blob/develop/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala#L315

Potential solution: do this as the service account instead.
