### ISSUE TITLE
Leo preemptible test fails in several different ways

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#228]
The test: "should execute Hail with correct permissions on a cluster with preemptible workers"

Example test output: https://fc-jenkins.dsp-techops.broadinstitute.org/view/Testing/view/Test%20Runners/job/leonardo-fiab-test-runner/400/console

Leo app log: https://fc-jenkins.dsp-techops.broadinstitute.org/job/fiab-stop/6335/artifact/logs/logs-20180301_150754/firecloud_leonardo-app_1.log

Sam app log: https://fc-jenkins.dsp-techops.broadinstitute.org/job/fiab-stop/6335/artifact/logs/logs-20180301_150754/firecloud_sam-app_1.log

First failure:
   - `"Multiple validation errors:\n - Insufficient 'CPUS' quota. Requested 52.0, available 24.0.\n - Insufficient 'IN_USE_ADDRESSES' quota. Requested 13.0, available 8.0."`

Second failure:
   - `[ERROR] [19:07:53.553] [leonardo-akka.actor.default-dispatcher-22] o.b.d.w.l.auth.LeoAuthProviderHelper - Auth provider SamAuthProvider throw an exception`
      - This might be due to Leo not cleaning up Sam resources on cluster errors. We may want to call `LeoAuthProvider.notifyClusterDeleted()` if cluster creation fails in Google, similar to how we delete the init bucket here: https://github.com/DataBiosphere/leonardo/blob/develop/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala#L285

I am not sure how to address the quota issue. Acceptance criteria of this ticket is make this test pass reliably.

**Comment by jmthibault79** [comment]
Re: `notifyClusterDeleted()`

In the case of cluster error we do call `internalDeleteCluster()` which transitions the cluster state to deleted.  The ClusterMonitorActor should then notice this, and call `notifyClusterDeleted()`

**Comment by jmthibault79** [comment]
See also the unsolved intermittent failure case in #204
