### ISSUE TITLE
Add New Relic to Leonardo

### ISSUE THREAD

**Issue by jmthibault79** [DataBiosphere/leonardo#232]
We recently added New Relic to other Workbench services but had problems in Leo, apparently due to a conflict with WebSockets.

See these comments for context: 
https://github.com/broadinstitute/firecloud-develop/pull/976#issuecomment-368156320
https://github.com/broadinstitute/firecloud-develop/pull/976#issuecomment-368332813

**Comment by vkumra-broad** [comment]
Update the DevOps playbook with New Relic info as part of this ticket.

https://docs.google.com/document/d/1n0KZuHFE7nb9OJsmT2YLger7w2yE3Zy3R_fsC-zNrUk
