### ISSUE TITLE
Using experimental App API to list with "includeDeleted" errors.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/leonardo#2357]
Setting "includeDeleted=true" here: https://leonardo.dsde-dev.broadinstitute.org/#/apps/listApp :

```
curl -X 'GET' \
  'https://leonardo.dsde-dev.broadinstitute.org/api/google/v1/apps?includeDeleted=true' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer ya29.blehblahbleh'
```

Causes this error:

```
{
  "source": "leonardo",
  "message": "DELETED is not a member of Enum (Creating, Restoring, Failed, Ready, Deleting, Deleted)",
  "statusCode": 500,
  "exceptionClass": "class java.util.NoSuchElementException",
  "traceId": null
}
```

**Comment by gpcarr** [comment]
> {
>   "source": "leonardo",
>   "message": "DELETED is not a member of Enum (Creating, Restoring, Failed, Ready, Deleting, Deleted)",
>   "statusCode": 500,
>   "exceptionClass": "class java.util.NoSuchElementException",
>   "traceId": null
> }

Thank you for bringing this to our attention! The team created a ticket to address this issue. [Here is the ticket](https://broadworkbench.atlassian.net/browse/IA-3034) in case you'd like to track it - we will triage it tomorrow morning

**Comment by DailyDreaming** [comment]
@gpcarr Thank you!

**Comment by Qi77Qi** [comment]
@DailyDreaming  there was some issue in our dev DB, it shouldn't happen in prod.... @jdcanas just fixed this today for dev..closing this issue for now, but let us know if you still see the problems
