### ISSUE TITLE
Support configurable delocalization to GCS

### ISSUE THREAD

**Issue by calbach** [DataBiosphere/leonardo#242]
Design under discussion @ https://docs.google.com/document/d/1GbaL1otgswBEOqfte8JO8uQDG_vSEG4a-qcKMEdufLI/edit?ts=5a9f0755#heading=h.vrxfsh4mwyvy

From talking with @rtitle yesterday, we think it will make sense to aim to build this as something deployed by default with Leonardo (though there would be no requirement to utilize it). I can prepare an initial PR for this once there is agreement on the doc.

**Comment by calbach** [comment]
Is there more to do here @rtitle ?

**Comment by rtitle** [comment]
Oh I think I reopened it to get it to display on our ZenHub "on dev" column. :) I think this ticket is done -- there is more to do to get it hooked up in FireCloud (I opened https://github.com/DataBiosphere/leonardo/issues/281 for that).
