### ISSUE TITLE
Automate periodic cluster purge

### ISSUE THREAD

**Issue by ansingh7115** [DataBiosphere/leonardo#243]
Joel currently runs a script every week that deletes all clusters in our development and testing environments, which is especially important for clusters that are orphaned by FiaBs. 

Automate this process so Joel doesn't have to do it.

**Comment by MatthewBemis** [comment]
1+ year later and we still don't have this automated.

+ @sharmatime - can we prioritize this in our tech debt bucket of work? should be relatively straightforward and quick to get this done. it's one less thing we'll have as overhead in our processes
