### ISSUE TITLE
Users unable to install R packages

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/leonardo#254]
User Alisa Manning reported being unable to install R packages from within their notebook. Got this error:

```
Installing package into ';/usr/local/lib/R/site-library';
(as ';lib'; is unspecified)
Warning message in install.packages(";ggplot2";):
";';lib = ";/usr/local/lib/R/site-library";'; is not writable";

Error in install.packages(";ggplot2";): unable to install packages
Traceback:

1. install.packages(";ggplot2";)
2. stop(";unable to install packages";)
```

**Comment by bradtaylor** [comment]
See gist for notebook html: https://gist.github.com/bradtaylor/ef58b1c3094f045016ca366cd6b54920

**Comment by helgridly** [comment]
Looks like the R install isn't writeable; I'd guess this is the R version of `pip install` doesn't work unless you add the `--user` flag. If R has an equivalent flag to install packages to some user-local directory then they should use that; otherwise they should use a userscript.

I recommend we also find a list of default packages to install with R like we do for Python. ggplot2 is definitely one of them.

**Comment by akmanning** [comment]
Users will always need to install new packages; and you should not assume that they will know how to specify another directory. It is not immediately obvious what directories are writable, anyway. We can use `!pip install <package>` inside a python notebook. We should be able to do something similar from within an R notebook.

**Comment by helgridly** [comment]
@akmanning We have a workaround for you.

Open a terminal inside Jupyter (New > Terminal):

```
$ mkdir .rpackages
$ echo "R_LIBS=/home/jupyter-user/.rpackages" > .Renviron
```

Then you can go ahead and do `install.packages` in an R notebook and it should install successfully.

We'll work on doing this by default in Leo but that should get you going again meanwhile.

**Comment by rtitle** [comment]
https://github.com/DataBiosphere/leonardo/pull/278 resolves this, so the above workaround won't be necessary after it's released.
