### ISSUE TITLE
Flaky unit test: should map non-LeoExceptions to LeoExceptions

### ISSUE THREAD

**Issue by jmthibault79** [DataBiosphere/leonardo#255]
This often fails and often passes:

[info] - should map non-LeoExceptions to LeoExceptions *** FAILED ***
[info]   A timeout occurred waiting for a future to complete. Queried 11 times, sleeping 15 milliseconds between each query. (ServiceAccountProviderHelperSpec.scala:55)

**Comment by rtitle** [comment]
Haven't seen this occur recently; closing
