### ISSUE TITLE
Load the R BigQuery package by default

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/leonardo#257]
Users of R notebooks will need access to data in BigQuery. The client package should be part of the standard data science packages we load.

https://www.google.com/url?q=https://cran.r-project.org/web/packages/bigrquery/index.html&sa=D&ust=1520984934954000&usg=AFQjCNE_TpTHn0esBsrR8Jk7MwKMqtIA1g

**Comment by bradtaylor** [comment]
Also dplyr 
https://cran.r-project.org/web/packages/dplyr/index.html

**Comment by rtitle** [comment]
https://github.com/DataBiosphere/leonardo/pull/278 resolves this
