### ISSUE TITLE
Cluster stuck in Creating status

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#262]
This affected Josh Mandel recently, and I think we've observed it in tests before too. Here is what I think happened in prod:

1. Cluster create API is called with `aou-test-f1-37/all-of-us`
2. API fails due to Sam 409 Conflict
   - Separate issue: there are a lot of Sam errors in Leo prod logs -- why?
3. Leo deletes cluster in Google and kicks off deletion monitor
4. Cluster create API is called _again_ with `aou-test-f1-37/all-of-us`
5. This time Sam succeeds
6. Cluster creation monitor is kicked off
7. The deletion monitor and creation monitor get mixed up and both hit `handleReadyCluster()`
8. When they both try to delete the init bucket they hit https://github.com/broadinstitute/workbench-libs/pull/90 (which Leo prod does not have yet).
9. End result is the cluster is still in Creating status and not being monitored

For this ticket:
- Try and repro this in a test
- Consume that workbench-libs change in Leo
- Review logic of what happens when a PUT /clusters call fails. Do we really need to trigger the deletion monitor?
- Investigate why Sam is throwing so many errors in the first place. I see many 500s and 409s.
- I also see a lot of (expected) stack traces from Sam during "list clusters" calls. Look into if we can suppress this somehow.

**Comment by calbach** [comment]
FYI I observed this a few hours ago on cluster `aou-test-f1-1557534645/all-of-us`. It was in the pending state for about 30-40m before I deleted it and recreated it.

**Comment by calbach** [comment]
Happened again this afternoon; cluster had the same name as above. For the log timestamps - I deleted it 1m ago to cancel the creation. I created it about 30m ago.

**Comment by rtitle** [comment]
Thanks CH. I think I have a good understanding of the underlying issue; working on a fix now.
