### ISSUE TITLE
Leo creating too many pets

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#263]
Example project: aou-test-f1-1

This project has 100 service accounts (the limit) including pets for Rob/Joel/Hussein/Brad who have never accessed this project. This is causing a lot of 500 errors in prod Sam/Leo. My theory is something in Leo (possibly the list clusters endpoint) is inadvertently creating pets in user projects for all cluster creators in the DB. We need to stop doing this.

**Comment by rtitle** [comment]
We should strive to _only_ use pets for offline access. When we have a token, we should use it.

**Comment by helgridly** [comment]
Your theory is correct. [`SwaggerSamClient` calls `resourcesApiAsPet`](https://github.com/DataBiosphere/leonardo/blob/06b7df6325f0265b5eef3c3c7d41cbd36b8d6d67/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/sam/SwaggerSamClient.scala#L137) which [ultimately calls Sam's `getUserPetServiceAccountKey`](https://github.com/DataBiosphere/leonardo/blob/06b7df6325f0265b5eef3c3c7d41cbd36b8d6d67/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/auth/sam/SwaggerSamClient.scala#L79). <-- blue is links to code

**Comment by rtitle** [comment]
Yeah here's what happens.
0. There are a bunch of clusters in the DB for many different projects
1. I go to the FireCloud notebooks tab which generates a Leo "list clusters" API
2. Leo iterates over _all_ clusters in the DB, and asks Sam one-by-one if I have permissions to see that cluster
3. Each Sam call creates a pet in that cluster's project
4. Everybody's project has too many pets

To fix it I am think of doing the following:
1. Use a token for Sam if it's not offline access (avoids creating pets we don't need).
2. Look at using a different Sam API for list clusters: https://sam.dsde-prod.broadinstitute.org/#!/Resources/listResourcePolicies. This gets ALL policies for the resource type. So we can make 1 Sam call and compare 2 lists instead of calling Sam for each cluster in the database.
