### ISSUE TITLE
FR: log user script output/result

### ISSUE THREAD

**Issue by calbach** [DataBiosphere/leonardo#265]
I'm specifying a `jupyterUserScriptUri` on cluster creation, and I'm certain the script is failing. The failure is silent and the notebook cluster starts anyways.

Would be nice if there were a log of what happened at startup accessible to clients, e.g. capturing the stderr of the startup script and/or logging the exit status of the script.

**Comment by rtitle** [comment]
For background, the dataproc init script is here:

https://github.com/DataBiosphere/leonardo/blob/develop/src/main/resources/jupyter/init-actions.sh

These are the scripts we run:

https://github.com/DataBiosphere/leonardo/blob/develop/src/main/resources/jupyter/init-actions.sh#L223-L224

We should change it so:
- errors running these scripts fail init-actions.sh with error status (causing the cluster to error out)
- we capture the output of these scripts. Writing it to stdout should be sufficient; we already capture the logs from `init-actions.sh`.

**Comment by rtitle** [comment]
PR https://github.com/DataBiosphere/leonardo/pull/393 should resolve this issue
