### ISSUE TITLE
Test failure: notebook couldn't access Spark context

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#268]
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/751/

Failing test: "ClusterMonitoringSpec.Leonardo clusters should create a cluster in a different billing project using PetClusterServiceAccountProvider and put the pet's credentials on the cluster"

![image.png](https://images.zenhubusercontent.com/5a6a47114b5806bc2bc454d7/5b46a720-2786-4f4f-99d3-5ec42a9482d9)

My speculation is that pyspark failed to initialize. Unfortunately we don't collect logs for this -- only the dataproc init logs which looked fine in this case. 

One idea is to run some notebook code in this test to grab Spark logs and save them to the test output, similar to what we do with dataproc initialization logs. Then we could at least see what went wrong and debug.

**Comment by jmthibault79** [comment]
Here's the PR that saved the init logs: #245
