### ISSUE TITLE
CORS headers are double-set for proxied Jupyter rest API

### ISSUE THREAD

**Issue by calbach** [DataBiosphere/leonardo#272]
Attempted to make a CORS request from my browser to the Jupyter REST API on the Leo cluster, and it fails due to invalid CORS header responses.

```
Failed to load https://notebooks.firecloud.org/notebooks/aou-test-f1-1/all-of-us/api/contents/workspaces/ecksdee: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost:4200, *', but only one is allowed. Origin 'http://localhost:4200' is therefore not allowed access.
```

From @rtitle, could consider:
- removing this line, if it doesn't break anything: https://github.com/DataBiosphere/leonardo/blob/develop/jupyter-docker/jupyter_notebook_config.py#L16
- or, switching this to be a replace rather than an append: https://github.com/DataBiosphere/leonardo/blob/develop/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/api/CorsSupport.scala#L26

I think either solution would work for me.

**Comment by rtitle** [comment]
I tried option 1 and it did break stuff. :) Got errors opening a notebook.

I think option 2 should be doable though; working on a test+fix.

**Comment by rtitle** [comment]
https://github.com/DataBiosphere/leonardo/pull/276
