### ISSUE TITLE
Allow use of OpenID Connect via the OIDC_CLAIM_sub which maps to OAuth2.0 claim of "user_id"

### ISSUE THREAD

**Issue by eap** [DataBiosphere/leonardo#303]
The module `org.broadinstitute.dsde.workbench.leonardo.api.StandardUserInfoDirectives` requires a header with `OIDC_CLAIM_user_id`. I've configured mod_auth_openidc and as best as I can tell, this isn't a standard claim, or, maybe I'm just missing the pertinent info on retrieving this claim.

Any thoughts? Is there a way to make the presence of this claim optional, or, if this claim a generally available feature of openid providers, can you document how to make this claim with mod_auth_openidc?

Edit:
After talking this through with David B. and reading through the mod_auth_openidc docs, I think I see the issue. mod_auth_openidc acts as a resource server when given a valid OAuth 2 bearer tokens and sends identity resources via the headers. Even though OpenID connect and Oauth2.0 provide many of the same identity resources some of them are sent under different names. In this case it seems that OIDC_CLAIM_user_id is the OAuth 2.0 version of OpenID Connect's OIDC_CLAIM_sub. 

It should be as simple as making this a config option. Alternatively we could check for the presence of either and use whichever one is present.

**Comment by eap** [comment]
Second note on compatibility - Leo currently relies on the "expires_in" return from OAuth 2.0 providers while openid provides expiration as a UTC timestamp.

**Comment by davidbernick** [comment]
We're still having an ongoing conversation in SLACK which might be helpful. I don't know enough about what Evan's working on but was explaining why our AuthN is set up as it is right now.

**Comment by eap** [comment]
Closing this bug - using oauth going forward sounds like the better option
