### ISSUE TITLE
Support localizing data URIs in addition to bucket paths

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#307]
`jupyter_localization_extension` currently supports localizing GCS paths. In case a bucket is not involved, it would be nice to pass the data to localize directly in the HTTP request. We could use a data URI for this (https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs).

**Comment by calbach** [comment]
I'd said I'd look into making a PR for this, but haven't started one yet. If anyone else can take this on, that would be great - otherwise I'll probably take a stab later this week.

**Comment by rtitle** [comment]
@zarsky-broad FYI

**Comment by rtitle** [comment]
I'll do this. I'm in this code anyway.

**Comment by calbach** [comment]
Thanks!
