### ISSUE TITLE
Jupyter kernel does not connect in Firefox

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#308]
It works in Chrome and Safari, but the kernel never connects in Firefox. This is probably due to websockets, in conjunction with the Leo proxy.

**Comment by calbach** [comment]
FWIW, I believe I've observed this sometimes in Chrome as well - I think, but it's been tricky to reproduce and seemingly only with certain versions (e.g. upgrading Chrome sometimes fixes). Nothing shows up in the Chrome console, so I assume it's websocket related.

**Comment by calbach** [comment]
FYI: My above comment may have been due to generally kernel unresponsiveness relating to https://github.com/DataBiosphere/leonardo/issues/321 (unconfirmed)
