### ISSUE TITLE
Jupyter server log access support/instructions

### ISSUE THREAD

**Issue by calbach** [DataBiosphere/leonardo#316]
We're frequently hitting an issue where kernel access appears to lock up. Would be nice to check server logs in this case to see what's going (or if that's already possible, instructions for doing this).

**Comment by danqrodney** [comment]
+1. It's frustrating when the kernel isn't working to have no idea what's going on. :)

**Comment by rtitle** [comment]
I'm working in the Leo init script anyway, thinking of piping Jupyter server logs to `~/jupyter.log`, which would be viewable from within a notebook/jupyter terminal.

**Comment by calbach** [comment]
Yes - that would be great. If possible, having this in a location that we can pull off the cluster (or delocalize, actually), would be great. Might need a slightly different workflow for that from the usual delocalization process.

**Comment by rtitle** [comment]
PR https://github.com/DataBiosphere/leonardo/pull/393 should resolve this issue. You should be able to access the log via a notebook or the Jupyter [contents API](https://github.com/jupyter/notebook/blob/master/notebook/services/api/api.yaml#L58). E.g. 

`GET https://leo/notebooks/project/cluster/api/contents/jupyter.log?content=1`
