### ISSUE TITLE
Pip install as user by default

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#322]
In a notebook, `pip install tensorflow` throws a permission error because the install directory is owned by root. `pip install tensorflow --user` works, but it's easy to forget to do that. Configure pip to install as user by default. Based on [pip docs](https://pip.readthedocs.io/en/1.1/configuration.html), this should be easily possible. It should work for both pip2 and pip3.

**Comment by jmthibault79** [comment]
May affect #324 ?
