### ISSUE TITLE
Support a standalone login flow for signed out users

### ISSUE THREAD

**Issue by calbach** [DataBiosphere/leonardo#326]
Possibly dependent on https://github.com/DataBiosphere/leonardo/issues/289. It would be good if Leo supported this, in cases where the Leo tab loses connectivity for >1h and can log itself back-in.

As a nice side-effect, this would serve as a catch-all for auth handoff issues across browsers. For example, cross-origin cookie setting is unsupported by default in the latest Safari.

**Comment by calbach** [comment]
@rtitle I think you said someone was working on this. Is there a different ticket tracking?

**Comment by rtitle** [comment]
Yes: https://github.com/DataBiosphere/leonardo/issues/206

**Comment by rtitle** [comment]
Closing in favor of #206
