### ISSUE TITLE
Cluster creation broken due to incorrect scopes used for CloudResourceManager

### ISSUE THREAD

**Issue by eap** [DataBiosphere/leonardo#332]
A recent change added the `getProjectNumber` utility function to leonardo.dao.google.HttpGoogleComputeDAO. This DAO also overrides scopes and sets them to the compute scopes. As a result all cluster create requests are failing with the error copied below. For now I've fixed this locally by substituting the much broader ComputeScopes.CLOUD_PLATFORM scope. This is a workable solution with the obvious security caveats, so I wanted to kick this back to ya'll in case you had a better fix in mind already.

As an aside, I'll mention that the resource manager API does require the cloud platform scope ([see here](https://cloud.google.com/resource-manager/docs/authorizing))

```
app_1       | [ERROR] [22:52:48.946] [leonardo-akka.actor.default-dispatcher-55] o.b.d.w.l.d.g.HttpGoogleComputeDAO - Call to Google API failed for kumo-notebook-workspace . Status: 403. Message: Request had insufficient authentication scopes.
app_1       | com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
app_1       | {
app_1       |   "code" : 403,
app_1       |   "errors" : [ {
app_1       |     "domain" : "global",
app_1       |     "message" : "Request had insufficient authentication scopes.",
app_1       |     "reason" : "forbidden"
app_1       |   } ],
app_1       |   "message" : "Request had insufficient authentication scopes.",
app_1       |   "status" : "PERMISSION_DENIED"
app_1       | }
```

**Comment by rtitle** [comment]
Opened https://github.com/DataBiosphere/leonardo/pull/338 to fix this issue. I think the reason we didn't notice it in FireCloud is that our code path doesn't call `getProjectNumber` (it's only used to get the compute default service account, but we use SAM).

**Comment by kyuksel** [comment]
I had to set the scope the same way for the same reason in my [soon-to-be PR](https://github.com/DataBiosphere/leonardo/compare/ky-leo-371#diff-ba2ce7c11315e461508bac3eee3f569eR39) and wasn't certain about the security implications myself.
