### ISSUE TITLE
Grant BigQuery roles when can-compute/can-notebook is given to a user

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#344]
We currently have a [Orch endpoint](https://api.firecloud.org/#!/Billing/grantGoogleRoleToUser) which grants Google IAM roles (e.g. bigquery.jobs.create) to a given user. It must be called by a project owner. However we'd like to automatically grant BQ roles when a user is given "can-notebook" permission. 

This will most likely involve a change to Rawls [UserService](https://github.com/broadinstitute/rawls/blob/develop/core/src/main/scala/org/broadinstitute/dsde/rawls/user/UserService.scala).

**Comment by bradtaylor** [comment]
Any update on this issue? It's currently causing a lot of manual work in Saturn

**Comment by rtitle** [comment]
We haven't scheduled it yet but it hasn't been forgotten. Can you quantify the amount of pain it's causing? Is there a deadline after which it _needs_ to be in the product (e.g. manual workarounds won't work anymore)? Just asking to help prioritize this against other work.

**Comment by rtitle** [comment]
Dupe of https://app.zenhub.com/workspace/o/databiosphere/saturn-ui/issues/202
PR: https://github.com/broadinstitute/rawls/pull/941
