### ISSUE TITLE
Handle zombie clusters

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#372]
When a user clicks on the UI link corresponding to a cluster they had created, if that cluster was deleted unbeknownst to Leonardo (e.g. on the Google Cloud console), the user gets the following error:

```
{"statusCode":500,"source":"leonardo","causes":[],"exceptionClass":"org.broadinstitute.dsde.workbench.leonardo.service.ProxyException","stackTrace":[],"message":"Unable to proxy connection to Jupyter notebook on general-dev-billing-account/james"}
```

At the least, we should return a more user-friendly message. Ideally, Leonardo should update its records to persist information about the situation, which can be useful for the error message displayed to the user as well as for future reference.

One possible implementation is to have an actor periodically cross-check the clusters recorded as running in the database against the Google Cloud. If a cluster appears to be running according to the database but doesn't exist on the cloud, the record should be updated to contain that information. This information then can be used by the Proxy endpoint to inform the user as necessary. Also think about what else might have happened to the cluster (besides being deleted) and see if that requires any different response in any way.

**Comment by MatthewBemis** [comment]
Closed. We have since implemented a zombie cluster monitor.
