### ISSUE TITLE
SPIKE: Discuss notebook downloading issues

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#384]
* Coordinate with the Comms team to make sure we respond to [Alisa's forum post](https://gatkforums.broadinstitute.org/firecloud/discussion/12012/notebook-r-kernel-exporting-downloading-notebooks#latest)
* Create tickets as necessary to address the post

**Comment by rtitle** [comment]
This ticket is a spike: determine what the current issues are with downloading notebooks in different formats (pdf, html, etc), and make tickets for the issues found.

**Comment by vkumra-broad** [comment]
I didn't find a graceful fix for it, currently it seems like the only way to get this to work is to install texlive but this increases the size of the docker image by > 1GB.

Jupyter documentation recommends a full Tex installation.
http://nbconvert.readthedocs.io/en/latest/install.html

**Comment by kyuksel** [comment]
Can it be installed via a user script instead?
