### ISSUE TITLE
Clusters are not immediately proxyable after resuming

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#385]
After a cluster transitions to Running after resuming, the notebook is not always proxyable. I think this is due to the Apache proxy on the master VM not reconnecting to the Jupyter server. We should find a way to ensure that a cluster is proxyable as soon as it transitions to Running.

**Comment by rtitle** [comment]
Fix this in 2 ways:
1. Tweak Apache settings to minimize initialization delay
2. Update monitoring to check Google AND Jupyter server health

**Comment by blrubenstein** [comment]
https://github.com/DataBiosphere/leonardo/blob/develop/automation/src/test/scala/org/broadinstitute/dsde/workbench/leonardo/LeonardoTestUtils.scala#L264
