### ISSUE TITLE
Relax master min disk boot size to match dataproc

### ISSUE THREAD

**Issue by calbach** [DataBiosphere/leonardo#388]
The current Leo docs say min disk is 100GB. It seems that dataproc has a 10GB minimum. Should make this match (I haven't checked whether it's just a documentation issue, or it's actually enforced):

https://github.com/DataBiosphere/leonardo/blob/develop/src/main/resources/swagger/api-docs.yaml#L721

**Comment by calbach** [comment]
Also, the docs should specify units for the master disk size

**Comment by rtitle** [comment]
More details about the changes here:

- I believe the minimum is actually set here: https://github.com/DataBiosphere/leonardo/blob/develop/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/model/LeonardoModel.scala#L172
- Update tests in LeonardoServiceSpec to verify the new minimum
- Update swagger docs here to reflect the new minimum and specify the units: https://github.com/DataBiosphere/leonardo/blob/develop/src/main/resources/swagger/api-docs.yaml#L721
- Manually create a cluster with a 10GB disk and make sure everything still works OK
