### ISSUE TITLE
Python BigQuery client is out of date

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/leonardo#392]
Google's python bigquery library changed significantly before the 1.0.0 release. Leo's currently installed version is 0.28. See here:
https://google-cloud-python.readthedocs.io/en/latest/bigquery/usage.html

Please update the python bigquery client to the latest. Google's usage examples don't work on the older version and their archived examples are not clear (or anyway, I couldn't get them to work).

**Comment by rtitle** [comment]
This affects the `google-cloud-sdk` installation in the Dockerfile. Need to figure out how to bump the bigquery version.

**Comment by bradtaylor** [comment]
Checking in- is there any expectation on completing this @rtitle ?

**Comment by kyuksel** [comment]
We expect to complete it by this quarter (Q3). If you need it by a certain date, let us know.
