### ISSUE TITLE
SPIKE: Figure out what is necessary to set up automated alerts

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#395]
Goals:
- make it easier to identify issues before/at the same time as users
- find issues in logs more easily

**Comment by kyuksel** [comment]
From the on-call training, Sentry looked promising to sign up for and customize alerts. Uncertain if it allows team-wide emailing (vs. personal only).

**Comment by rtitle** [comment]
Proposal: 
- Use sentry for alerting Leo/cluster errors
- Investigate if we can create a Sentry filter for Leo exceptions
- Investigate if all Leo exceptions are actually hooked up to Sentry (cluster coming up wiht Error for example)

**Comment by MatthewBemis** [comment]
Let's roll this into the New Relic bucket of work
