### ISSUE TITLE
Support running user scripts against a Running cluster

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#397]
Currently user scripts can only be run at cluster initialization time. However with apps like Saturn pre-creating clusters for users at registration time, they'd like the ability to run scripts against Running cluster. Support this in Leo via a new (PATCH?) endpoint.

**Comment by rtitle** [comment]
Needs a tech doc -- how to actually run scripts against a Running VM? Research GCE metadata, etc for ways to do this.

**Comment by rtitle** [comment]
This might be covered by https://github.com/DataBiosphere/leonardo/issues/413. In that scenario you could stop a cluster, and pass a script to run at cluster start time.

**Comment by MatthewBemis** [comment]
Closing in favor of giving root access to users. See #840
