### ISSUE TITLE
Add 'tidyverse' to the set of R packages installed by default

### ISSUE THREAD

**Issue by deflaux** [DataBiosphere/leonardo#401]
Its generally useful for data wrangling and includes a whole bunch of core packages such as ggplot2.

Book for users http://r4ds.had.co.nz/
All the packages under the tidyverse umbrella https://www.tidyverse.org/

**Comment by deflaux** [comment]
sorry, looks like I accidentally closed this, reopening!

**Comment by rtitle** [comment]
Notes from refinement:
1. Quantify the impact here -- what is the added size to the docker image, and how much time does it save on cluster creation?
2. Investigate if tidyverse duplicates any R packages that we currently install, and if we can now remove them.
