### ISSUE TITLE
Create Jenkins build to periodically clean up clusters 

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#402]
...that were created as part of tests and not cleaned up.

**Comment by vkumra-broad** [comment]
I gave this a shot and it doesn't seem to be as straightforward as I thought. 

Ran into issues with passing the credentials to the jenkins job. It would need SA credentials we currently run the script as: 

```./cleanup_clusters.sh delete qa thibault@quality.firecloud.org```

**Comment by MatthewBemis** [comment]
closing as duplicate of https://github.com/DataBiosphere/leonardo/issues/243
