### ISSUE TITLE
Install the table of contents notebook extension by default

### ISSUE THREAD

**Issue by deflaux** [DataBiosphere/leonardo#404]
This will allow us to embed Python or R code inline in Markdown cells using `{{ my-variable }}` notation.
https://stackoverflow.com/a/43912180

```
pip install jupyter_contrib_nbextensions
jupyter nbextension install ~/.local/lib/python3.4/site-packages/jupyter_contrib_nbextensions/nbextensions/python-markdown --user
jupyter nbextension enable python-markdown/main
```

**Comment by deflaux** [comment]
Please also add the [configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) and [Table of Contents 2](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html) extensions.

```
pip install jupyter_contrib_nbextensions jupyter_nbextensions_configurator
jupyter nbextensions_configurator enable --user

jupyter nbextension install ~/.local/lib/python3.4/site-packages/jupyter_contrib_nbextensions/nbextensions/toc2 --user
jupyter nbextension enable toc2/main
```

**Comment by deflaux** [comment]
The table of contents notebook extension is generally useful to all projects. It helps people navigate through long notebooks. https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html

I'm updating the name of this issue to install the table of contents extension by default. (the markdown extension is lower priority).

**Comment by mbookman** [comment]
Yes, please.

I have started enabling the TOC in all of my notebooks and it makes for a much better user experience.

**Comment by kaitlinhagan** [comment]
I agree that this would also save me time.
