### ISSUE TITLE
Add scope for Cloud Source Repository Reader to Leonardo instances

### ISSUE THREAD

**Issue by deflaux** [DataBiosphere/leonardo#408]
Docs https://cloud.google.com/source-repositories/docs/configure-access-control

perhaps this is the right place? https://github.com/DataBiosphere/leonardo/blob/41e4c201b9ab9bf653604b13130c9b0ce9c033a8/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/dao/google/HttpGoogleDataprocDAO.scala#L212

**Comment by rtitle** [comment]
Agreed that's the right place. Taking this, I think we can get this into tomorrow's release. cc @bradtaylor

**Comment by rtitle** [comment]
PR: https://github.com/DataBiosphere/leonardo/pull/409

Testing it now

**Comment by rtitle** [comment]
Merged - will be in the FC release tomorrow.
