### ISSUE TITLE
Add ability to run custom script on resume

### ISSUE THREAD

**Issue by danqrodney** [DataBiosphere/leonardo#413]
After a cluster is un-paused, it's useful to be able to run a custom script that can sync code or data to the 
cluster. (This will allow us to automatically upgrade client libraries, JupyterLab extensions, etc.)

Clients should be able to specify this when creating or updating a cluster's metadata.

Vaguely related to:

https://github.com/DataBiosphere/leonardo/issues/397

@rtitle

**Comment by rtitle** [comment]
Proposal: add this script as field in the startCluster endpoint. Leo would install it in GCE metadata so it runs at VM start time.

**Comment by rtitle** [comment]
Needs tech doc
