### ISSUE TITLE
Update FireCloud Notebooks' online documentation

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#415]
Once [the changes revamping the FireCloud UI for Notebooks](https://github.com/DataBiosphere/leonardo/issues/281) are on Prod, [the FireCloud online documentation](https://software.broadinstitute.org/firecloud/documentation/article?id=11603) will be outdated. In fact, parts of [the page on limitations](https://software.broadinstitute.org/firecloud/documentation/article?id=11603) may already be outdated, and should also be updated.

**Comment by rtitle** [comment]
Question: can we direct users to Saturn for their notebooks needs?

**Comment by MatthewBemis** [comment]
Closed as comms owns this now and FireCloud UI is no longer supported
