### ISSUE TITLE
Auto pause : Prevent auto pause when kernel is active

### ISSUE THREAD

**Issue by vkumra-broad** [DataBiosphere/leonardo#437]
Jupyter exposes an api end point `/api/sessions` that lists the status of the kernel. 

This can be used to prevent auto pausing clusters that have a long running job running on it.

Sample response from Jupyter:

`[{"kernel": {"connections": 1, "last_activity": "2018-06-21T16:50:26.147483Z", "execution_state": "busy", "id": "80be095a-b5b6-4f48-b5eb-e7f619d365b6", "name": "pyspark2"}, "name": "", "notebook": {"path": "Untitled.ipynb", "name": ""}, "path": "Untitled.ipynb", "type": "notebook", "id": "046d77bb-af4b-45f2-98d5-522aa8a9a33f"}]`

**Comment by Qi77Qi** [comment]
this is closed with #874 

There could be future improvements like if user had bad code that puts kernel in infinite loop, we can potentially alert user if their kernel has been running for a long time.
