### ISSUE TITLE
Allow Leo to create Dataproc clusters in a subnet

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#472]
Currently Leo is configured to use project-defaults for VPC/subnet when creating clusters: 

https://github.com/DataBiosphere/leonardo/blob/develop/src/main/resources/reference.conf#L9

We use project-defaults because we currently don't create any VPC/subnets, and we need to ensure the network exists in the user's project. We should move to doing a little more network management, and create a subnet _ourselves_ for the Dataproc cluster. This opens the door to some security features needed for NIH. @davidbernick has more info.

**Comment by kyuksel** [comment]
Please document the relevant information for future developer reference in [Leonardo Developer Handbook](https://docs.google.com/document/d/1i7C5NBOMYMGjJ1cOkhSRXXn-sqA-S8hYH3AeVfhAP1U/edit#).

**Comment by rtitle** [comment]
RT: look at adding security work to this Q's OKRs and bumping something else off.

**Comment by davidbernick** [comment]
This is actually been made high priority by NIH AoU infosec team. They need us to be able to monitor the traffic via a SIEM. To do that, we need the traffic. This should enable me to get the traffic out and put it in a SIEM. We need it long before the public launch.

**Comment by rtitle** [comment]
Thanks @davidbernick - based on this we're prioritizing it higher. We'll update when we start work on this.

**Comment by davidbernick** [comment]
What's ETA on this?

**Comment by rtitle** [comment]
End of Q4

**Comment by davidbernick** [comment]
So that’s end of December?

**Comment by davidbernick** [comment]
https://broadinstitute.atlassian.net/plugins/servlet/mobile#issue/GAWB-4001 For tracking coordination with the rest of Workbench.

**Comment by rtitle** [comment]
cc @dvoet @gjordan (I don't know Greg's github identity)

My understanding is that the original design as written in this ticket has changed. Instead of Leo creating subnets when it creates clusters, Rawls will create the networks during project creation (ideally using deployment manager). Leo (and Cromwell?) can then be configured to use the correct networks when launching compute. This all needs to happen before AllOfUs athens launch in March. Cloud Accounts is starting this work on the Rawls side now and Leo team will coordinate.

**Comment by davidbernick** [comment]
Can we cross reference all Cloud Account tickets here?
