### ISSUE TITLE
500 Error when downloading notebook as ipynb

### ISSUE THREAD

**Issue by vkumra-broad** [DataBiosphere/leonardo#486]
Recreation steps : File->Download as->Notebook(ipynb)

This is the error that we get 
<img width="936" alt="screen shot 2018-07-17 at 9 17 35 am" src="https://user-images.githubusercontent.com/30244225/42819938-e4acd492-89a2-11e8-9f5e-08ac5cca3bf0.png">

This is the jupyter log error details
<img width="1143" alt="screen shot 2018-07-17 at 9 16 49 am" src="https://user-images.githubusercontent.com/30244225/42819961-f4bdff5a-89a2-11e8-81a3-2739ddb63c7c.png">

There are two jupyter issues about this bug as well 

https://github.com/jupyter/notebook/issues/3769
https://github.com/jupyter/notebook/issues/3734

**Comment by kyuksel** [comment]
It is [reported](https://github.com/jupyter/notebook/issues/3769#issuecomment-417881591) that the issue has been fixed with [this Jupyter PR](https://github.com/jupyter/nbconvert/pull/873).

**Comment by rtitle** [comment]
Test again with the latest Jupyter pulled in by the Dockerfire.

**Comment by sharmatime** [comment]
Sean mentioned he recently saw this 500 error when downloading a notebook:

![screenshot 2018-11-13 at 11 45 56 pm](https://user-images.githubusercontent.com/6709226/48738242-54c26480-ec1e-11e8-8148-09166cd61a73.png)

**Comment by vkumra-broad** [comment]
I _think_ this issue has been fixed in the newer version of jupyter. @akarukappadath can you check if the Dockerfire/Jupyterlab changes fixed this issue as well?
