### ISSUE TITLE
Reduce the size of the Jupydocker image by cleaning the apt cache

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#492]
I think there might be opportunities to reduce our image size. For example we have multiple layers doing `apt-get update && apt-get install ...`. These layers don't clean the apt cache when they're done, so they end up being huge. Try cleaning the apt cache at the end of every layer, and see what kind of size reduction that buys us.

**Comment by vkumra-broad** [comment]
Reduces the docker image size by about 100MB
