### ISSUE TITLE
Reader can create cluster

### ISSUE THREAD

**Issue by andy7i** [DataBiosphere/leonardo#497]
Reader without can-compute access can create a cluster in Firecloud. 

Repro steps:
- share a workspace with a user with Reader access. Ensure that the Reader is not a billing project owner.
- open the workspace with the Reader. Open the Notebook tab.
- The Create Cluster button is enabled. Click it and try to create a cluster.
- A cluster is created.

Expected: the button should be disabled for users who should not have access.

Should also verify that a user gets the same results via API.

**Comment by andy7i** [comment]
this works for both Readers with Can Share and without it.

**Comment by MatthewBemis** [comment]
Closed. Project level permissions are what govern cluster permissions, not workspace level permissions.
