### ISSUE TITLE
Token cookie refresh seems to not always be working

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#501]
@helgridly noticed this when using the Jupyter terminal from FireCloud. Is there something weird about the terminal where it doesn't load the extension?

Other users of Saturn have complained about this more generally. Is Saturn initializing the timer correctly via postMessage handshake?

For this ticket, investigate the above issues and make fixes as needed.

**Comment by rtitle** [comment]
Note: an easy way to test if the extension is working is watching the Network tab in the browser console. It should be making a call to google every 2 mins

**Comment by zarsky-broad** [comment]
Observed: left a notebook open for several minutes, both in an iframe and in its own tab. Saw zero requests to google.

**Comment by rtitle** [comment]
Closing this in favor of #289.
