### ISSUE TITLE
Flipping from a Jupyter terminal tab to another browser tab and back makes the terminal contents vanish

### ISSUE THREAD

**Issue by helgridly** [DataBiosphere/leonardo#515]
With the old terminal installed, hitting return made it reappear. It doesn't now (post W release, presumably #461), but the prompt shows up.

**Comment by akarukappadath** [comment]
I'm having a little trouble reproducing this issue, could you give me some more information?

**Comment by helgridly** [comment]
Upgrading my browser fixed it.
