### ISSUE TITLE
SPIKE: Investigate the JupyterLab URL bug

### ISSUE THREAD

**Issue by blrubenstein** [DataBiosphere/leonardo#518]

**Comment by blrubenstein** [comment]
https://app.zenhub.com/workspace/o/databiosphere/leonardo/issues/474

**Comment by rtitle** [comment]
Posting results in the other ticket: https://github.com/DataBiosphere/leonardo/issues/474

**Comment by akarukappadath** [comment]
Tech Doc: https://docs.google.com/document/d/1L3KPlG-HDcHFEEma6YDwXrw1U8S9f_c0FC5reYbuGRc/edit
