### ISSUE TITLE
SPIKE: design for including custom R package in Leo

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#520]
Output of this ticket is a tech doc for Issue #434 which should be reviewed by Nicole Deflaux.

**Comment by rtitle** [comment]
@vkumra-broad I attached a notebook from Nicole D that has the R code that we want to package. It is this:
```
# Authorize bigrquery client
BILLING_PROJECT_NAME <- Sys.getenv('GOOGLE_PROJECT')

# Delete this after https://github.com/DataBiosphere/leonardo/issues/434
token <- system("gcloud auth application-default print-access-token", intern=TRUE)
bearer <- sprintf("Bearer %s", token)
project <- Sys.getenv("GOOGLE_PROJECT")
samHost <- "sam.dsde-prod.broadinstitute.org"  # note this is PROD; replace with dev Sam in a dev notebook
samUrl <- sprintf("https://%s/api/google/user/petServiceAccount/%s/key", samHost, project)
json <- httr::GET(
  url = samUrl,
  httr::content_type_json(),
  httr::add_headers(Authorization = bearer))
key <- httr::content(json, "text", encoding = "UTF-8")

set_service_token(key)
```
What I think this work will entail:
1. Make a place under `jupyter-docker` in Leo for R code
2. Review the R code above -- I hacked it together in a few minutes, it should probably be made into a function and cleaned up a little.
2. Create whatever R scripts are needed to make the above function into a package (googling "how to make an R package" returns a bunch of results).
3. Build & install the package in the Dockerfile
4. Write some automation tests in `NotebookRKernelSpec` that use the package -- e.g. they successfully authenticate with bigrquery and run some queries.

**Comment by rtitle** [comment]
Ah well I can't attach ipynb files -- the full notebook is named `Rbigquery.ipynb` in this bucket: https://console.cloud.google.com/storage/browser/fc-4205396d-2cde-4436-8903-9b374dac5bbf/notebooks

**Comment by kyuksel** [comment]
👍 for [the tech doc](https://docs.google.com/document/d/125TKZtTlDbbOlsrfxthlJM_-VQCX7g7G46r3l_vzBwo/edit?usp=sharing_eil&ts=5b919bf8)
