### ISSUE TITLE
GET cluster 404 with PUT cluster v2

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#528]
During the integration testing of the new v2 PUT cluster API, when a new cluster is created and then immediately queried with the GET endpoint, tests got 404 ClusterNotFound errors even though querying on Swagger at the same time returned the expected response. Once a 404 response is received, tests continue getting 404s with subsequent attempts even after a while, which may point to caching somewhere.

**Comment by rtitle** [comment]
@kyuksel @blrubenstein once this issue is fixed (or understood enough that we're confident it won't cause problems in production), then you can let the AoU team know they can start using it in this ticket:

https://precisionmedicineinitiative.atlassian.net/browse/RW-580
