### ISSUE TITLE
Add 'cloud-platform' scope to Leonardo VMs

### ISSUE THREAD

**Issue by deflaux** [DataBiosphere/leonardo#542]
This allows users with their own project to use Leonardo as their 'lab notebook' to dispatch work to other systems available on cloud platform.

**Comment by rtitle** [comment]
Hi @deflaux (cc @davidbernick),

Today Leo sets user/email (for FireCloud APIs) and bigquery scopes on all clusters by default. I don't think we want to add 'cloud-platform' scopes to _all_ Leo clusters by default -- in particular for AoU we need to limit the scopes that we request.

So I think we need to design a more granular way of setting these scopes -- either per user, per app (e.g. Saturn, AoU, etc), or ideally per dataset. I'm actually curious about your use case: are you using Leo standalone or through Saturn in this scenario? If standalone, then maybe we could add a server-side config for the scopes we put on clusters. If through Saturn, then we'd need to find some other mechanism.

**Comment by deflaux** [comment]
Both!

For my standalone use cases, I have access to the VM and can add that scope myself.

Its the Saturn use cases where this is blocking me from using Leonardo as my 'lab notebook' when I want to kick off analyses in my own cloud project using systems such as https://github.com/DataBiosphere/dsub and https://cloud.google.com/ml-engine/docs/tensorflow/technical-overview

**Comment by davidbernick** [comment]
As long as AoU users are restricted from having these scopes it’s fine for other users to have them. Leonardo/FC documentation about how pet service accounts are used and restricted should be updated.

**Comment by blrubenstein** [comment]
AC: Users can specify scopes at cluster creation time. Automation test.

**Comment by blrubenstein** [comment]
Open question: Are there any scopes we could grant that break our security model? What scopes do we want to allow to enable?

**Comment by davidbernick** [comment]
Please note what I said about aou users.

**Comment by blrubenstein** [comment]
@davidbernick I believe what the team talked about in refinestimation is that the default behavior would be the minimal set of scopes we grant right now, and then the apps can decide if they want to pass up extra scopes at cluster creation time. @rtitle to confirm if I am correct here.

**Comment by davidbernick** [comment]
I’m great with that -/ thanks!

**Comment by seanhorgan** [comment]
Great to see this move forward. When you say "apps", do you mean Terra versus All of Us? 

Control at the Terra/All of Us level will work in the short-term (next 6 months) but I could imagine a specific org using Terra applying a similar scope restriction just for their users.

**Comment by rtitle** [comment]
Yes by apps I mean clients of Leo (Terra, All Of Us, FireCloud, etc). The scopes will be configurable in Leo at cluster creation time. In a sense we're pushing responsibility to the app -- e.g. Terra can have an app-wide setting or allow more granular control by users. For a first pass I'm envisioning Terra granting CLOUD_PLATFORM by default, then potentially fine-tuning if different users have different requirements.

**Comment by seanhorgan** [comment]
Thanks Rob. I'll defer to Nicole on the exact scopes she believes that Terra should support by default so we can support running other tools from those VMs.
