### ISSUE TITLE
Capture Notebook actions in audit log

### ISSUE THREAD

**Issue by davidbernick** [DataBiosphere/leonardo#545]
This is NOT urgent like some other audit related tasks but this is something the NIH isn't backing down from. We need a way to log the actions that are happening in a Notebook. We know this is not a forensic panacea but they still want it to catch "low hanging fruit". Logs will need to be written out to stdout for capture, but alternative ways of capturing (pubsub events, fluentd, etc) are ok too.

This might be a good starting point? https://github.com/ipython/ipython/issues/8570

**Comment by rtitle** [comment]
Another option might be for the Leo proxy to log all notebook code executed through the websocket (which should be plaintext at the Leo service level). Need to weigh pros and cons of Leo-centric and Jupyter-centric approaches.

**Comment by davidbernick** [comment]
Yeah -- I offer no opinion on this other than it needs to be done at some point. As I said, it's not urgent but the Feds want it.
