### ISSUE TITLE
Kernel frequently dies during GATK/FireCloud workshop

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#547]
It happened to about 50% of attendees on 8/27. Reconnecting the kernel seems to fix it, but it shouldn't be dying in the first place.

Browser logs: 
https://broadinstitute.slack.com/files/U0EN53PQB/FCFB5JV96/screen_shot_2018-08-27_at_2.48.48_pm.png

Jupyter logs on 1 of the clusters:

```
jupyter-user@filter-tutorial-m:~$ cat jupyter.log 
[I 18:31:27.394 NotebookApp] initializing DelocalizingContentsManager
[I 18:31:27.397 NotebookApp] Writing notebook server cookie secret to /home/jupyter-user/.local/share/jupyter/runtime/notebook_cookie_secret
[W 18:31:27.583 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 18:31:27.583 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 18:31:27.593 NotebookApp] initialized jupyter_localize_extension
[I 18:31:27.595 NotebookApp] Serving notebooks from local directory: /home/jupyter-user
[I 18:31:27.595 NotebookApp] The Jupyter Notebook is running at:
[I 18:31:27.595 NotebookApp] http://(filter-tutorial-m or 127.0.0.1):8000/notebooks/fccredits-niobium-pink-5002/filter-tutorial/
[I 18:31:27.595 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 18:31:51.450 NotebookApp] 302 GET /notebooks/fccredits-niobium-pink-5002/filter-tutorial (127.0.0.1) 0.66ms
[I 18:33:03.505 NotebookApp] Uploading file to /GATK Tutorial - Hard Filtering.ipynb
[I 18:33:03.521 NotebookApp] Writing notebook-signing key to /home/jupyter-user/.local/share/jupyter/notebook_secret
[I 18:33:08.220 NotebookApp] Kernel started: de9a613b-36a8-4c15-a9a0-f2b8ce6a5370
[I 18:33:08.734 NotebookApp] Adapting to protocol v5.1 for kernel de9a613b-36a8-4c15-a9a0-f2b8ce6a5370
[I 18:35:08.736 NotebookApp] Starting buffering for de9a613b-36a8-4c15-a9a0-f2b8ce6a5370:0cf90a2f7fb448d08640721f3cd44f85
[I 18:41:08.064 NotebookApp] Adapting to protocol v5.1 for kernel de9a613b-36a8-4c15-a9a0-f2b8ce6a5370
[I 18:41:08.065 NotebookApp] Restoring connection for de9a613b-36a8-4c15-a9a0-f2b8ce6a5370:0cf90a2f7fb448d08640721f3cd44f85
[I 18:41:08.170 NotebookApp] Saving file at /GATK Tutorial - Hard Filtering.ipynb
[I 18:42:24.778 NotebookApp] Starting buffering for de9a613b-36a8-4c15-a9a0-f2b8ce6a5370:0cf90a2f7fb448d08640721f3cd44f85
[I 18:42:25.205 NotebookApp] Kernel restarted: de9a613b-36a8-4c15-a9a0-f2b8ce6a5370
[I 18:42:25.945 NotebookApp] Adapting to protocol v5.1 for kernel de9a613b-36a8-4c15-a9a0-f2b8ce6a5370
[I 18:42:25.946 NotebookApp] Restoring connection for de9a613b-36a8-4c15-a9a0-f2b8ce6a5370:0cf90a2f7fb448d08640721f3cd44f85
[I 18:42:25.946 NotebookApp] Replaying 6 buffered messages
[I 18:43:08.353 NotebookApp] Saving file at /GATK Tutorial - Hard Filtering.ipynb
[I 18:44:25.950 NotebookApp] Starting buffering for de9a613b-36a8-4c15-a9a0-f2b8ce6a5370:0cf90a2f7fb448d08640721f3cd44f85
[I 18:45:32.038 NotebookApp] Adapting to protocol v5.1 for kernel de9a613b-36a8-4c15-a9a0-f2b8ce6a5370
[I 18:45:32.039 NotebookApp] Restoring connection for de9a613b-36a8-4c15-a9a0-f2b8ce6a5370:0cf90a2f7fb448d08640721f3cd44f85
[I 18:47:08.170 NotebookApp] Saving file at /GATK Tutorial - Hard Filtering.ipynb
[I 18:47:32.049 NotebookApp] Starting buffering for de9a613b-36a8-4c15-a9a0-f2b8ce6a5370:0cf90a2f7fb448d08640721f3cd44f85
[I 18:47:44.162 NotebookApp] Adapting to protocol v5.1 for kernel de9a613b-36a8-4c15-a9a0-f2b8ce6a5370
[I 18:47:44.163 NotebookApp] Restoring connection for de9a613b-36a8-4c15-a9a0-f2b8ce6a5370:0cf90a2f7fb448d08640721f3cd44f85
[I 18:47:44.163 NotebookApp] Replaying 1 buffered messages
[I 18:49:08.148 NotebookApp] Saving file at /GATK Tutorial - Hard Filtering.ipynb
[I 18:49:44.173 NotebookApp] Starting buffering for de9a613b-36a8-4c15-a9a0-f2b8ce6a5370:0cf90a2f7fb448d08640721f3cd44f85
[I 18:50:29.408 NotebookApp] Adapting to protocol v5.1 for kernel de9a613b-36a8-4c15-a9a0-f2b8ce6a5370
[I 18:50:29.409 NotebookApp] Restoring connection for de9a613b-36a8-4c15-a9a0-f2b8ce6a5370:0cf90a2f7fb448d08640721f3cd44f85
[I 18:51:08.184 NotebookApp] Saving file at /GATK Tutorial - Hard Filtering.ipynb
[I 18:52:29.419 NotebookApp] Starting buffering for de9a613b-36a8-4c15-a9a0-f2b8ce6a5370:0cf90a2f7fb448d08640721f3cd44f85
[I 18:53:07.724 NotebookApp] Adapting to protocol v5.1 for kernel de9a613b-36a8-4c15-a9a0-f2b8ce6a5370
[I 18:53:07.724 NotebookApp] Restoring connection for de9a613b-36a8-4c15-a9a0-f2b8ce6a5370:0cf90a2f7fb448d08640721f3cd44f85
[I 18:55:07.772 NotebookApp] Starting buffering for de9a613b-36a8-4c15-a9a0-f2b8ce6a5370:0cf90a2f7fb448d08640721f3cd44f85
[I 18:55:08.344 NotebookApp] Saving file at /GATK Tutorial - Hard Filtering.ipynb
[I 18:55:21.800 NotebookApp] Adapting to protocol v5.1 for kernel de9a613b-36a8-4c15-a9a0-f2b8ce6a5370
[I 18:55:21.801 NotebookApp] Restoring connection for de9a613b-36a8-4c15-a9a0-f2b8ce6a5370:0cf90a2f7fb448d08640721f3cd44f85
[I 18:55:29.091 NotebookApp] Starting buffering for de9a613b-36a8-4c15-a9a0-f2b8ce6a5370:0cf90a2f7fb448d08640721f3cd44f85
[I 18:55:29.412 NotebookApp] Kernel shutdown: de9a613b-36a8-4c15-a9a0-f2b8ce6a5370
[I 18:55:29.543 NotebookApp] Kernel started: c24a5b67-ea33-4b7a-b1d9-e62d657f1942
[I 18:55:30.394 NotebookApp] Adapting to protocol v5.0 for kernel c24a5b67-ea33-4b7a-b1d9-e62d657f1942
```

**Comment by rtitle** [comment]
Maybe the websocket is dying?

**Comment by rtitle** [comment]
Note: this could be related to https://github.com/DataBiosphere/leonardo/issues/546.

The kernel seems to be dying every 2 minutes on the dot, regardless of kernel activity. We initially suspected google_sign_in.js which is 1m and 2m timers. However we added logging and changed those timer periods, and observed they have no effect on the kernel dying after 2m. So it must be something else.

I don't see any suspicious errors in Leo logs. There are some 404s for preact.js in Jupyter logs -- not sure if that is related.

Another process that happens every 2 minutes is auto-saving a notebook. That's another thing to look at...

**Comment by rtitle** [comment]
Things I tried that didn't work:
- Disabling CSP
- Disabling notebook autosave
- Running Jupyter in debug mode (didn't show anything useful)

I found an old cluster created Aug 3 -- I'm now checking if it's reproducible there.

**Comment by tmm211** [comment]
Hi Rob, not sure if this is helpful, but just wanted to add context. When I ran this tutorial on my own, I didn't run into these errors. It first came up when we ran it with multiple people at the same time, on different gcp projects, and in different workspaces.

**Comment by rtitle** [comment]
Update: I think this is related to a LB setting. We only recently (on 8/26) put Leo behind a LB in prod. Basically Google LBs use a "response timeout" setting to kill HTTP and websocket connections, regardless of whether they're idle!

See: https://cloud.google.com/load-balancing/docs/https/#websocket_proxy_support
> The timeout for a WebSocket connection depends on the configurable response timeout of the load balancer, which is 30 seconds by default. This timeout is applied to WebSocket connections regardless of whether they are in use or not. For more information about the response timeout and how to configure it, refer to Timeouts and retries.

For us the response timeout was set to 2 minutes, which is consistent with what we were seeing: all websockets were being killed after exactly 2 minutes. To work around this issue, we are increasing it to 4 hours. Google suggests increasing it for long-lived websocket connections. It would be nice if there were separate settings for http vs websocket. The only downside to this increase should be extra memory/resources on the LB, which should be ok given Leo's usage pattern.

I hope that 4h is sufficiently long to prevent most users from hitting this issue. Another approach we could take is to see if we can make Jupyter UI automatically reconnect broken websockets. This might take significant extra effort though since we don't control the Jupyter UI.

**Comment by ahaessly** [comment]
i would like to see a more obvious error or warning when this does happen instead of the broken link. it took a bit of time for us to figure out we weren't connected. it looked like the request was executing. It might also be nice to have a hover tip over the broken link saying to reconnect or actually if just clicking on the broken link would try the reconnect

**Comment by rtitle** [comment]
^ Good ideas, might be worth tracking in a follow-on ticket. Also I wonder how broken kernels are displayed in JupyterLab..

**Comment by rtitle** [comment]
We pushed the LB fix to prod last night, and the issue seems to be resolved. I successfully ran kernels last night for 3+ hours until they died (which could have been due to some other reason -- I'm still investigating this). I'm closing this ticket since the original issue is resolved. Rob M and I are continuing to look into networking settings though to ensure that long-lived kernels stay open.
