### ISSUE TITLE
Jupyter frontend extensions specified by url?

### ISSUE THREAD

**Issue by zarsky-broad** [DataBiosphere/leonardo#555]
When initializing a cluster, it would be really helpful to be able to specify an http url for a .js file to have it added as an extension. That way, it can be checked in to code and we can be sure the correct version is always served alongside our application.

**Comment by bradtaylor** [comment]
Having to package extensions as a tarball in GCS makes it difficult to deploy/test extensions we develop.

**Comment by rtitle** [comment]
@zarsky-broad this is in prod now.
