### ISSUE TITLE
Update gpalloc to scrub clusters from billing projects

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#559]
This is the gpalloc repo: https://github.com/broadinstitute/gpalloc. See the readme for documentation.

GPAlloc has functionality to "scrub" billing projects when they are put back in the pool. The code is here:

https://github.com/broadinstitute/gpalloc/blob/develop/src/main/scala/org/broadinstitute/dsde/workbench/gpalloc/dao/HttpGoogleBillingDAO.scala#L134

We want to enhance this logic to also clean up dataproc clusters. This will help ensure that tests don't "leak" clusters, spending money.

@helgridly offered to give additional pointers on this. :)

**Comment by helgridly** [comment]
feel free to come poke me if you have questions!
