### ISSUE TITLE
Deploy front/back Leos

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#565]
Work with DevOps to have the Jenkins deployment infrastructure set the config parameter that determines the Leo mode (front or back) based on the GCE host. We should be able to follow the mechanism used for distinguishing front- and back-Rawls.

**Comment by blrubenstein** [comment]
AC: We have a front- and back- leo on GCE, and we have the ability to deploy front- and back- Leo's with a click of a button in Jenkins
