### ISSUE TITLE
Tech-doc load testing

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#567]
Write a tech doc on load testing Leo. It should contain two main pieces of information:

1. What scenarios should we load-test? It would be helpful to get feedback from Leo UI/UX folks. Some points to consider:

- what use cases do we care the most about and want to make sure we’re content with their performance?
- what is the load that would require more than one front Leo?
- what is the load that would require having database read replicas?

2. How to implement the tests? 

- Can we leverage the Workbench perf environment?
- What frameworks exist out there and how do they differ for our purposes?

**Comment by rtitle** [comment]
This is our existing framework for FireCloud load testing: https://github.com/broadinstitute/mcnulty

We should look into adding Leo test cases to this repo.

**Comment by kyuksel** [comment]
Also, albeit not related to horizontal scaling, consider adding a load testing scenario for the cases where we schedule tasks (e.g. related to auto-freezing clusters) recurrently. In such cases, if the scheduled work takes long enough, it could create pathological executions such as:

- t=0: We schedule a task to determine and auto-pause the clusters that can be auto-paused.
- t=30: We issue a stop request for a cluster that was determined to be auto-pausable.
- t=60: Another task is scheduled to determine and auto-pause clusters.
- t=90: We make another stop request for a cluster that was in progress for being stopped but hasn't completed yet.

**Comment by kyuksel** [comment]
[Tech doc](https://docs.google.com/document/d/1b1baxAwaNMy71nLr3VZggQ6jo-UiCIk_GtpccdmYtuI)
