### ISSUE TITLE
Frequent timeouts pulling the notebooks image from GCR

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#570]
See Takeaway #2 here: https://docs.google.com/document/d/1qrqI4V18YuKTaX1zsJ6YugKg7lwD0W9jmZPn-jF88RQ/edit

We see frequent test failures like:
```
Monitoring Cluster status: ClusterName(automation-test-ayd5mqyzz) Error was not equal to Running
```

Dataproc logs show:
```
GCR timeout: Get https://us.gcr.io/v2/broad-dsp-gcr-public/leonardo-notebooks/manifests/dev: dial tcp 108.177.112.82:443: i/o timeout
```

Job links:
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/4240/
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/4239/

Look into retrying the GCR pull in case of errors. We could also look at upgrading to the latest docker-compose as part of this.

**Comment by rtitle** [comment]
I'm going to take a crack at this

**Comment by rtitle** [comment]
See Jackie's PR for ideas on how to make the GCR pull more robust: https://github.com/broadinstitute/firecloud-develop/pull/1345/files#r218572099

There may be some ideas we can borrow, namely:
1. Using `timeout x docker-compose ... || compose_good=$?` and checking the error status
2. Running `docker-compose config`, `docker-compose pull`, and `docker-compose up -d` as separate commands

**Comment by rtitle** [comment]
See test spreadsheet which tracks the frequency of test failures (this one is Row 6): https://docs.google.com/spreadsheets/d/1cmdiunXTOCHGtjZrSZvP0LbWmpWxVqeQgDroXIzFyJc/edit#gid=0

**Comment by aweng98** [comment]
reoccured on 9/24/2018 4 PM. https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/9748/

**Comment by rtitle** [comment]
Arg I don't think the retries are working because `set -e` makes bash exit immediately when there's an error. It should be doing something like
```
docker-compose pull ... || docker_failed=$?
```
Will look at making another PR..
