### ISSUE TITLE
UI: Attempting to delete somebody else's UI results in undesirable error message

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#572]
I see the error below on the new UI (on `dev` as of this writing) when I attempt to delete the `Untitled` notebook in the team's `callisto-dev/Callisto-Test` workspace. Instead, we should probably alert the user that they aren't allowed to delete a notebook they don't own (or don't have writing privileges - whatever the appropriate UX jargon might be).

![image (1).png](https://images.zenhubusercontent.com/5abe9f1b4b5806bc2bcd152f/96efeda4-e1cf-4dc8-b162-a29dcdd49130)

**Comment by rtitle** [comment]
Addressed in PR: https://github.com/broadinstitute/firecloud-ui/pull/1423
