### ISSUE TITLE
Support GPU-enabled clusters

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#573]
Dataproc lets you attach GPUs to clusters:

https://cloud.google.com/dataproc/docs/concepts/compute/gpus?hl=ru

However this functionality is not supported in Leonardo. We should support it.

(This was a Saturn user question, not necessarily high priority.)

**Comment by rtitle** [comment]
I actually started to do this work. My branch is here: https://github.com/DataBiosphere/leonardo/tree/rt-gpu

Basically I got as far as extending the Leo API to include GPUs and spinning up GCE instances with GPUs attached. However to actually utilize the GPU on the machine you need the correct drivers. See:
 
https://cloud.google.com/compute/docs/gpus/add-gpus
https://cloud.google.com/dataproc/docs/concepts/compute/gpus

The above links have steps to install the drivers but debian is not a supported OS 😢 . Another option would be to try launching our Dockerfile with [nvidia-docker](https://github.com/NVIDIA/nvidia-docker). This is actually what @kyuksel's team is doing.

**Comment by kyuksel** [comment]
Thanks for giving this a shot, @rtitle! 

> The above links have steps to install the drivers but debian is not a supported OS.
Bummer! We _do_ use Ubuntu.

> Another option would be to try launching our Dockerfile with nvidia-docker. This is actually what @kyuksel's team is doing.

We're actually using both `docker` and `nvidia-docker` depending on whether the VM is GPU-enabled or not via

```bash
${DOCKER_COMMAND} run ${INTERACTIVE} \
--rm \
--ipc=host \
-v /home/${USER}/jupyter/root/:/root/ \
-v /home/${USER}/:/home/${USER}/ \
-v /mnt/:/mnt/ \
${DOCKER_IMAGE} python "$@"
```
where `DOCKER_COMMAND` can be either and nothing else has to change. 

Our `Dockerfile` is pretty bare bones, too:

```
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Setup time zone (or else docker build hangs)
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./config/* /app/

WORKDIR /app

# Basic setup
RUN ./ubuntu.sh

# FastAI. See the Developer Install under https://github.com/fastai/fastai/ to
# understand this odd sequence of installing then uninstalling fastai before 
# installing it from github. (Basically, to get its deps.)
RUN pip3 install -r fastai-requirements.txt
RUN pip3 uninstall -y fastai
RUN ./fastai.sh

# Requirements for the tensorflow project
RUN pip3 install -r tensorflow-requirements.txt

# Other requirements
RUN pip3 install -r other-requirements.txt
```

This may also be a use case for Bring-Your-Own-Docker-Image if it were possible to layer it over the Leo image.
