### ISSUE TITLE
Notebooks not localizing to the cluster

### ISSUE THREAD

**Issue by vkumra-broad** [DataBiosphere/leonardo#577]
I got a 404 when I tried opening a notebook

Steps to recreate the issue
1. Create new notebook(n1)
2. Create new cluster(c1)
3. Associate n1 to c1
4. Create new notebook(n2)
5. Associate n2 to c1
6. Wait till cluster is ready
7. Open n1 - I got a 404
8. Open n2, works fine

**Comment by rtitle** [comment]
Addressed in PR: https://github.com/broadinstitute/firecloud-ui/pull/1423
