### ISSUE TITLE
Async cluster creation does not handle Leo restarts well

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#578]
Leo can get into a bad state when the service restarts while there is an async cluster creation in process. For example this came up:

1. createCluster is called, record is inserted to the DB with status = Creating and googleId = NULL
2. google creation is kicked off asynchronously
3. Leo restarts _after_ the cluster is created in Google but _before_ the google id is written back to the Leo DB
4. BootMonitors starts monitoring all Creating clusters
5. when cluster transitions to Running, ClusterDnsCache throws an `AssertionError` because the googleId is null
6. actor system shuts down because a fatal error was thrown

We should have a way to cleanly recover if Leo restarts while an async creation is in process. Perhaps we could retry the creation, or just flip the status to ERROR and force clients to retry.

**Comment by kyuksel** [comment]
Also think about other Leo-restart-related cases like the one above that may have been overlooked.

**Comment by kyuksel** [comment]
We may be able to fix the reported issue by adding a check to `ClusterMonitorActor`'s `preStart()` routine such that if the cluster is `Running` (or `Creating` | `Updating` ?), we read its `googleId` (and the other fields persisted at the same time as `googleId`) for it in the database. The flow of calls in `ClusterMonitorActor` is:

`preStart()` => `scheduleInitialMonitorPass` => `QueryForCluster` => `checkCluster`

`checkCluster` could be the place to do the check.

**Comment by rtitle** [comment]
The scenario to consider is:
1. cluster is created in the Database (in Creating status)
2. cluster is NOT created in Google

How do we recover from this case?

**Comment by vkumra-broad** [comment]
https://docs.google.com/document/d/1sT72uADqbkKNbb46hEa23g_H-Thucr6YsxEuFPhahMg/edit?ts=5c350a2d
