### ISSUE TITLE
Async cluster creation errors on the Google side is not conveyed to the user appropriately

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#590]
For instance, with the async API, when a user specifies an invalid cluster name, the API call is still completed with `202` since it doesn't know, at the completion time, of the naming error it ends up getting from Google (with the non-async API, we return a `500` with the appropriate error message). When we try to `GET` the cluster, we see a `404 Cluster Not Found` error, so the user has no way of knowing what went wrong. This is a general problem with the async nature of the Google cluster creation. 

At the least, I'd recommend we
- enter an error record for the cluster in the database so `GET` calls can display it to the user
- validate cluster names and fail the `PUT` call as necessary since that's probably a frequent error user would make

**Comment by kyuksel** [comment]
Correction: A record in `CLUSTER_ERROR` table *is* created appropriately and returned on the `GET` response. The scope of this ticket is, to decide if it's worth validating cluster naming on our end for better user experience and if so, to implement it.

**Comment by rtitle** [comment]
I think I see the issue: when an async error occurs we persist an error in the DB but we do NOT set the cluster status to Error (it remains in Creating). The cluster JSON then looks like this (note it has an error but the status is still Creating): 
```
{
  "autopauseThreshold": 30,
  "instances": [],
  "errors": [
    {
      "errorMessage": "Asynchronous creation of cluster 'CLUSTER' on Google project 'callisto-dev' failed due to 'org.broadinstitute.dsde.workbench.model.WorkbenchException: Call to Google API failed for callisto-dev / CLUSTER. Status: 400. Message: Cluster name 'CLUSTER' must match pattern (?:[a-z](?:[-a-z0-9]{0,49}[a-z0-9])?)'.",
      "errorCode": -1,
      "timestamp": "2018-09-21T13:34:32Z"
    }
  ],
  "machineConfig": {
    "numberOfWorkers": 0,
    "masterMachineType": "n1-standard-4",
    "masterDiskSize": 500
  },
  "creator": "rtitlefireclouddev@gmail.com",
  "googleProject": "callisto-dev",
  "id": 20217,
  "labels": {
    "clusterServiceAccount": "pet-114686604539784786127@callisto-dev.iam.gserviceaccount.com",
    "clusterName": "CLUSTER",
    "creator": "rtitlefireclouddev@gmail.com",
    "googleProject": "callisto-dev"
  },
  "dateAccessed": "2018-09-21T13:34:26.155Z",
  "status": "Creating",
  "clusterUrl": "https://leonardo.dsde-dev.broadinstitute.org/notebooks/callisto-dev/CLUSTER",
  "clusterName": "CLUSTER",
  "serviceAccountInfo": {
    "clusterServiceAccount": "pet-114686604539784786127@callisto-dev.iam.gserviceaccount.com"
  },
  "createdDate": "2018-09-21T13:34:26.155Z"
}
```

Relevant code: https://github.com/DataBiosphere/leonardo/blob/develop/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/service/LeonardoService.scala#L539

We should fix the above method to ALSO set the cluster status to Error. I think that should resolve https://github.com/DataBiosphere/leonardo/issues/582 as well.

**Comment by rtitle** [comment]
I made a PR for the above: https://github.com/DataBiosphere/leonardo/pull/592
