### ISSUE TITLE
FC UI: Validate cluster name input

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#599]
This came up at a recent workshop and FireCloud demos. Users would like fewer restrictions around cluster naming. (Currently we require lower case characters, dashes, etc which are limitations from Dataproc.)

One idea is to do a mapping between user-specified name and cluster name. We could have 2 database columns `clusterName` and `userClusterName`. The latter would be what's presented to users and the former would be what is created in Dataproc. We could generate the `clusterName` from `userClusterName` and ensure it meets Dataproc requirements.

**Comment by kyuksel** [comment]
@ahaessly @tmm211 What were the mostly commonly failing characters that the Sevilla workshop participants used?

**Comment by tmm211** [comment]
I don't remember, but I'd guess upper-case letters and underscores.

**Comment by kyuksel** [comment]
> in saturn, if a user wants to create a new cluster, do they also have these
issues?

I believe Saturn creates clusters for users and names them under the hood so I don't think the naming issue applies to Saturn users. Perhaps @bradtaylor can correct me if I'm wrong.

**Comment by MatthewBemis** [comment]
Closed. FC UI no longer being supported
