### ISSUE TITLE
Clone workspace should copy notebooks

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#601]
In FC and Saturn, notebooks are stored in a `notebooks` subdirectory of the workspace bucket. For example:
```
gs://fc-e8ba5c4e-2e45-4e58-98e2-3594a1eba9a7/notebooks/test.ipynb
```

We should make workspace clone _copy_ the notebooks in the source workspace to the destination workspace. We can probably copy all files matching the pattern: `notebooks/*.ipynb`.

The relevant code is in Rawls, around here: https://github.com/broadinstitute/rawls/blob/e12bbdf31726d00b35a4a6eecf2c9cb7312708e4/core/src/main/scala/org/broadinstitute/dsde/rawls/workspace/WorkspaceService.scala#L381

This is needed for the FireCloud workshop at ASHG in October, but will benefit Saturn as well.

**Comment by kyuksel** [comment]
I wonder if it'd be valuable to copy data files that may be in the _notebooks_ directory, too.

**Comment by vkumra-broad** [comment]
I talked to @rtitle  about the data file, we will start with just the notebooks and can iterate over the data files, if needed.

**Comment by kyuksel** [comment]
Are we planning on releasing this feature prior to the ASHG workshop? If so, I wonder if it'd be too risky.

**Comment by kleighwe** [comment]
@bradtaylor this should be unblocked! The work Andrea did is on Alpha.

**Comment by calbach** [comment]
Note: AoU currently implements this logic on top of Rawls clone. We would prefer not to do this ourselves. It would be great if this were implemented in an opt-in way so we could stage the change on our end (as 
a boolean, or possibly as a list of paths per discussions today). I do have concerns about our clone breaking if this Rawls behavior suddenly went live.
