### ISSUE TITLE
UI: Error loading notebooks upon coming back to browser after a while

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#602]
I believe it consistently happens. Not sure how long of leaving the browser/tab it takes to cause this.

![image.png](https://images.zenhubusercontent.com/5abe9f1b4b5806bc2bcd152f/d52f3920-b2cf-4af0-b830-637c16d9370e)

Console:

![image.png](https://images.zenhubusercontent.com/5abe9f1b4b5806bc2bcd152f/fa7948dd-40e1-4e02-826d-d2811f844674)

It seems to be continuously trying to localize and fail.

![image.png](https://images.zenhubusercontent.com/5abe9f1b4b5806bc2bcd152f/2783ab61-65cc-4d84-b088-f8eb0f5b21f0)

Refreshing the page fixes the issue.

**Comment by rtitle** [comment]
Potentially related or duplicated by https://github.com/DataBiosphere/leonardo/issues/608

**Comment by rtitle** [comment]
@kyuksel to test and update the ticket with current behavior.

**Comment by kyuksel** [comment]
I no longer see localization calls but we're still calling `setCookie` and getting `401`s repeatedly as shown below. I'm not sure if this warrants increasing the priority level or not, @rtitle.

<img width="1674" alt="image" src="https://user-images.githubusercontent.com/5438223/47502052-e19f1b80-d834-11e8-8a78-e4eadd17affd.png">

**Comment by MatthewBemis** [comment]
Closing because this is a FireCloud issue
