### ISSUE TITLE
Automatically convert to html

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#603]
This is a usability improvement. Currently read-only members of the workspace have no way to preview notebooks because they can't create a cluster (this is true for all the apps: FC, Saturn, and AoU).

Enhancement: update `jupyter_delocalize.py` to automatically nbconvert the notebook to html and delocalize that alongside the ipynb file. Then the UIs will be able to implement a "read-only" notebook view by simply loading the html file.

**Comment by kyuksel** [comment]
Saturn may no longer need this so closing for now.
