### ISSUE TITLE
Add API to restart Jupyter

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#604]
This is a user pain point: if Jupyter gets into a bad state, the user must recreate their cluster which can take up to 15 minutes. Leo could provide an API to forcibly restart the Jupyter server process to handle such situations.

**Comment by sharmatime** [comment]
@calbach Rob and I were discussing this - Do you recall much about this issue? Have you heard of it happening since?

**Comment by calbach** [comment]
There are probably 2 relevant scenarios here where this might help.

1. User does something in the notebook that causes 100% CPU/RAM usage on the cluster, thereby making the UI unresponsive. The process may not ever finish and the user has to restart the whole thing to recover. I don't know whether this ticket would cover that as the VM may not be responsive at all in this scenario given the current configuration.
2. I believe we've only confirmed this happening once, but there was a situation where the Jupyter docker process actually died on the VM, recreating was the only option for recovery.
