### ISSUE TITLE
Repeated frequent Ajax calls by the UI on an idle page

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#608]
### Impact
* difficulty using `Console` for development
* potentially reliability issues

### Problem

Doing nothing on the notebooks UI main page as shown below

![image.png](https://images.zenhubusercontent.com/5abe9f1b4b5806bc2bcd152f/3d82e9dd-1ccc-4657-8b1f-55c61e5389de)

and looking at `Console`, seeing very frequent calls being made to the following APIs:
- GET /api/clusters
- POST /notebooks/api/localize
- GET /setCookie

and hence the warnings below:

![image.png](https://images.zenhubusercontent.com/5abe9f1b4b5806bc2bcd152f/7242c777-853e-47e5-aa37-7017ca81da53)

**Comment by kyuksel** [comment]
This issue might be the culprit in the increased logging that can be seen in this [Kibana query](https://kibana.logit.io/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(_source),index:'*-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'host:gce-leonardo-prod*%20AND%20422')),sort:!('@timestamp',asc))):

![image](https://user-images.githubusercontent.com/5438223/46359010-43090b80-c636-11e8-8567-e480c57ff008.png)

**Comment by rtitle** [comment]
This should hopefully be fixed by https://github.com/broadinstitute/firecloud-ui/pull/1432
