### ISSUE TITLE
Cloud Dataproc API has not been used

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#613]
While investigating the significant increase in logging reported by DevOps, I noticed that ~3% of it is due to errors like

```
Cloud Dataproc API has not been used in project 451960624917 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/dataproc.googleapis.com/overview?project=451960624917 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
```

Kibana query:

https://kibana.logit.io/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:'*-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'host:gce-leonardo-prod*%20AND%20%22Cloud%20Dataproc%20API%20has%20not%20been%20used%22')),sort:!('@timestamp',asc))]

Note the jump around the 9/12 release below:

![image.png](https://images.zenhubusercontent.com/5abe9f1b4b5806bc2bcd152f/5b9b758c-bb87-4aee-8d0a-474327c980c1)

**Comment by kyuksel** [comment]
From the app logs in prod, the issue stems from this code in Leo:

```
[ERROR] [16:49:49.885] [leonardo-akka.actor.default-dispatcher-33880] o.b.d.w.l.m.ClusterMonitorActor - Error occurred monitoring cluster test-fc-billing-nmc/saturn-ecbe493e-3fa2-4b8a-b3ff-2c3a3d681711
org.broadinstitute.dsde.workbench.model.WorkbenchException: Call to Google API failed for test-fc-billing-nmc / saturn-ecbe493e-3fa2-4b8a-b3ff-2c3a3d681711. Status: 403. Message: Cloud Dataproc API has not been used in project 986418293680 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/dataproc.googleapis.com/overview?project=986418293680 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

**Comment by rtitle** [comment]
There was a fix made last week to abort monitoring error'd clusters. Need to confirm whether this is still an issue.

**Comment by rtitle** [comment]
Should be resolved by zombie cluster monitoring: now it should detect clusters in a bad state and abort monitoring. Closing; re-open if this is still an issue.

**Comment by kyuksel** [comment]
The issue appears to have persisted with an uptick for the last couple of days (Oct 23-25) but still lower than around Sep 29:

![image](https://user-images.githubusercontent.com/5438223/47510114-7447b680-d845-11e8-853e-fed34f7e3d6e.png)

**Comment by kyuksel** [comment]
The errors all seem to stem from one project with `project 85852348362`, which corresponds to the project `workshop-cptac`, which is used by FireCloud workshops apparently.

![image](https://user-images.githubusercontent.com/5438223/48083266-c3390880-e1c2-11e8-9c24-43c6cd048a93.png)

**Comment by abhishek-ksolve** [comment]
google.api_core.exceptions.PermissionDenied: 403 Cloud Dataproc API has not been used in project 61XXXXXX54 before or it is disabled. 
I tried to run a data proc job from the cloud function, but I throws the above error.
