### ISSUE TITLE
UI: Wrong cluster name isn't displayed properly as an error

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#634]
We saw this at the ASHG workshop where the error wouldn't be displayed as expected.

**Comment by kyuksel** [comment]
It would be ideal and the most interactive for the UI to alert the user as soon as they type an invalid character. In case it helps, [this PR](https://github.com/broadinstitute/firecloud-ui/pull/1040/files) does something similar for method configuration names.

**Comment by rtitle** [comment]
Scope this ticket to the FC UI changes to prevent invalid cluster names.

Create new ticket to do additional validation on the Leo server side.

**Comment by sharmatime** [comment]
I talked to Ilyana about this - she said she wasn't concerned about the error in firecloud and that it should be fixed in Terra instead.

**Comment by sharmatime** [comment]
Closed because we're no redirecting users to Terra
