### ISSUE TITLE
SPIKE: Tech doc for Leo restarts during async cluster creation

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#641]
See ticket: https://github.com/DataBiosphere/leonardo/issues/578

**Comment by rtitle** [comment]
Note: it might be worth checking out how Rawls submission monitoring handles this.

**Comment by vkumra-broad** [comment]
Tech doc: https://docs.google.com/document/d/1sT72uADqbkKNbb46hEa23g_H-Thucr6YsxEuFPhahMg/edit?ts=5c350a2d
