### ISSUE TITLE
Deflakegate : Add status check to the localization extension

### ISSUE THREAD

**Issue by vkumra-broad** [DataBiosphere/leonardo#652]
The localize extension calls `gsutil cp` which sometime will hang and recover in it's own sweet time. It might be better to do a quick check to make sure that we are copying a file that exists and the user has access to it. 

The code lives here : https://github.com/DataBiosphere/leonardo/blob/develop/jupyter-docker/custom/jupyter_localize_extension.py

Test this multiple times, this is an issue that has caused our tests to be flakey.

If this does not work, another option worth considering is adding a timeout to the `run_sync` call: https://www.tornadoweb.org/en/stable/ioloop.html. This could cause issues with copying large files.

**Comment by kyuksel** [comment]
For some reason this was moved to `In Progress` and assigned to Vikram. I've moved it back to `Backlog` as I'm not aware of any work done on it and Vikram will be out for a while.
