### ISSUE TITLE
Leo DB queries are case-insensitive

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#653]
As shown on the screenshot below, we get a confusing message when a user enters an invalid cluster name in the cluster creation request, saying that the cluster already exists. 

![image.png](https://images.zenhubusercontent.com/5abe9f1b4b5806bc2bcd152f/b95f7da6-5f5b-400d-a27e-b7126c944fbb)

This happens because we are using a case-insensitive collation

```
MySQL [leonardo]> SELECT @@collation_database;
+----------------------+
| @@collation_database |
+----------------------+
| utf8_general_ci      |
+----------------------+
```

as a result the mysql query

```
SELECT * from CLUSTER where clusterName ="UPPER-CASE-CLUSTER";
```

gets turned into 
```
SELECT * from CLUSTER where clusterName ="upper-case-cluster";
```

and if `upper-case-cluster` happens to have been previously created, the user gets the shown message.

There are at least two ways to make such queries case-sensitive:
1. Update queries to include `COLLATE`; e.g. `SELECT * from CLUSTER where clusterName COLLATE  'utf8_general_cs' = "UPPER-CASE-CLUSTER";` if the specified `collation` is defined
2. Update the database to set a case-sensitive collation, which is more preferable so queries don't have to be changed

**Comment by MatthewBemis** [comment]
Closing. We're going to keep things case-insensitive
