### ISSUE TITLE
Update Python 3 to a more recent version.

### ISSUE THREAD

**Issue by deflaux** [DataBiosphere/leonardo#663]
The Leonardo image currently has Python 3.4.2.

We'd like to be able to use [Ibis](https://docs.ibis-project.org/getting-started.html) but it [requires a working Python 2.7 or 3.5+ installation](https://docs.ibis-project.org/getting-started.html).

From https://cloud.google.com/community/tutorials/bigquery-ibis

> Ibis is a Python library for doing data analysis. It offers a Pandas-like environment for executing data analysis in big data processing systems such as Google BigQuery. Ibis's primary goals are to be a type safe, expressive, composable, and familiar replacement for SQL.

**Comment by rtitle** [comment]
cc @sharmatime @akarukappadath 

We are close to finishing a PR which upgrades the image to Python 3.6, as well as a slew of other libraries. We will communicate when this is closer to landing but my estimate would be in mid to late November.
