### ISSUE TITLE
Establish baseline performance figures for Leo

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#664]
It would be great to establish a baseline *before* we merge in horizontal scaling changes so we can detect regressions, if any. We probably won't have the production performance tests in place by the time we merge in the first couple of horizontal scaling tickets. I'm opening this ticket to see if we can opportunistically run the prototype tests ad-hocly...perhaps by time-boxing it to a day or two.

**Comment by rtitle** [comment]
Decision: run the fully automated perf tests when available for consistency in results. We can investigate running against an older version for comparison.
