### ISSUE TITLE
Prevent kernel disconnections upon idling for an hour or more

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#670]
A user reported that their kernel disconnects upon coming back to their notebook after an hour or more. We should improve this user experience if possible.

The disconnect may be due to our [akka.http.server.idle-timeout config](https://github.com/broadinstitute/firecloud-develop/blob/dev/base-configs/leonardo/leonardo.conf.ctmpl#L63) set to `1 hour`. It seems like this setting governs both http and websocket connections. It could be ideal to not have a timeout for websocket connections, which may be possible by using the `akka.http.server.websocket.periodic-keep-alive-max-idle` parameter.

From the related [documentation](https://doc.akka.io/docs/akka-http/current/configuration.html):

```
# Interval for sending periodic keep-alives
# The frame sent will be the one configured in akka.http.server.websocket.periodic-keep-alive-mode
# `infinite` by default, or a duration that is the max idle interval after which an keep-alive frame should be sent
# The value `infinite` means that *no* keep-alive heartbeat will be sent, as: "the allowed idle time is infinite"
    periodic-keep-alive-max-idle = infinite
```

**Comment by vkumra-broad** [comment]
PR: https://github.com/broadinstitute/firecloud-develop/pull/1459
