### ISSUE TITLE
Test Failure: Jupyter kernel not ready after timeout

### ISSUE THREAD

**Issue by MatthewBemis** [DataBiosphere/leonardo#676]
https://broadworkbench.atlassian.net/browse/WB-81

**Comment by sharmatime** [comment]
Hi @MatthewBemis. I'm wondering if this still an issue?

**Comment by MatthewBemis** [comment]
@sharmatime it was marked as resolved on the QA board yesterday as it hasn't been seen since Dec 4th 😄 

i think it's safe to close this
