### ISSUE TITLE
User/service account and Google project creation

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#679]
Please see the [Performance Testing tech doc](https://docs.google.com/document/d/1b1baxAwaNMy71nLr3VZggQ6jo-UiCIk_GtpccdmYtuI) for context.

**Victory condition:** Leo performance tests have a way to allocate and de-allocate a configurable number of accounts and Google projects.

At the beginning of a Leo performance test, we will need to be able to create service accounts and 
add them to Google projects. We should be able to leverage [GPAlloc](https://github.com/broadinstitute/gpalloc) to allocate projects without having to create new ones each time, and de-allocate them as part of the clean-up at the end of the test run. We’ll probably need to create a separate (perf) GPAlloc.

At least for this first phase, we will want to assign each user a distinct project as was the use case for the ASHG workshop and will likely be a realistic scenario for Terra and AoU as well. It also allows for stress-testing Leonardo by submitting numerous cluster creation requests simultaneously, which we wouldn’t be able to if we reuse projects for different users since it causes errors on the Google side due to concurrent IAM policy changes, etc. To the best of our knowledge, Saturn and All of Us also currently have one cluster per project model.

[service_account_user_test-aj.sh](https://github.com/broadinstitute/mcnulty/blob/aj-ashg-workshop/service_account_user_test-aj.sh) is a good start to generate the accounts. It might make sense to write it in Scala so we could keep a map of (project, username) in memory. It should then be possible to create a [Gatling feeder](https://gatling.io/docs/2.3/session/feeder/) out of that map, which can be attached to the Gatling scenario described below.

**Comment by MatthewBemis** [comment]
Closing in favor of newly created performance testing tickets.
