### ISSUE TITLE
SPIKE: How to make websocket calls for performance testing

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#682]
Please see the [Performance Testing tech doc](https://docs.google.com/document/d/1b1baxAwaNMy71nLr3VZggQ6jo-UiCIk_GtpccdmYtuI) for context.

**Victory condition:** We found out (and documented as necessary) if it’s feasible to simulate the websocket calls (that we make, for instance, when executing notebook cells) in a performance test (ideally using Gatling).

**Comment by MatthewBemis** [comment]
Closing in favor of newly created performance testing tickets.
