### ISSUE TITLE
Performance test clean-up

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#683]
Please see the [Performance Testing tech doc](https://docs.google.com/document/d/1b1baxAwaNMy71nLr3VZggQ6jo-UiCIk_GtpccdmYtuI) for context.

**Victory condition:** The tests are be idempotent, leaving everything as found. 

For this purpose, we need to
- remove/deallocate user/service accounts and Google projects
- delete clusters (using the DELETE endpoint)
- delete buckets
produced/allocated by the tests.

**Comment by MatthewBemis** [comment]
Closing in favor of newly created performance testing tickets.
