### ISSUE TITLE
Refactor the simulation class and the configs

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#686]
At this point, it should be clear how to refactor the Leo-specific configs and the Scala code. It will probably make sense to have a LeonardoSimulation class that extends FirecloudSimulation and is extended by Leo tests.

**Victory condition:** Leo-specific configs and common code is factored out of the test code as well as non-Leo-specific Firecloud code.

**Comment by MatthewBemis** [comment]
Closing in favor of newly created performance testing tickets.
