### ISSUE TITLE
Make cluster PATCHING horizontally scalable

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#687]
**Victory condition:** We can PATCH clusters in a horizontally scalable way.

We have a [PR](https://github.com/DataBiosphere/leonardo/pull/669) to add a PATCH endpoint to update cluster configurations. This code will also need to be modified similarly to DNSCache and ClusterMonitorActor as explained in [Leo Horizontal Scaling Implementation Plan](https://docs.google.com/document/d/1KQ4BSEQvrvdArDVvr8dupO9t9g3ksql41FCONNh3Yeg). The gist of it is to not message ClusterMonitorSupervisor while processing the PATCH request, and instead, to make sure the newly scheduled ClusterMonitorSupervisor task that scans the database infers that the cluster being updated needs to be monitored and acts accordingly.

**Comment by vkumra-broad** [comment]
This should be handled by https://github.com/DataBiosphere/leonardo/pull/689
