### ISSUE TITLE
Add ability to specify Jupyter and/or RStudio images in the createCluster request

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#696]
Add 2 new optional fields to createCluster:
* jupyterDockerImage
* rstudioDockerImage

Default to current behavior: install Jupyter but not RStudio

Add CLUSTER_IMAGE table to the Leo DB:
* Cols: clusterId (fkey), tool (str), dockerImage (str)
* Other metadata needed?
* Intent of this table is to track what image(s) are installed on a cluster

Leo createCluster code inserts to the above table and templates the images into init-actions.sh as an array 

Make a cluster-docker-compose.yml per tool (right now we have only one)

Update init-actions to call each docker-compose.yml based on the images passed to it

PR: https://github.com/DataBiosphere/leonardo/pull/691

**Comment by rtitle** [comment]
Deployed to production! This means it's possible today to spin up rstudio (open source) in prod. It's not documented in swagger yet and has no persistence.
