### ISSUE TITLE
UI: Doesn't inform users of malformed user script URIs 

### ISSUE THREAD

**Issue by kyuksel** [DataBiosphere/leonardo#703]
We had this situation while doing testing for the Taiwan workshop where we copied a `gs://...` URI that links to a user script, from the worksheet pdf, and pasted into the cluster creation dialog on FireCloud UI. This copy/pasting introduced unintentional characters to the beginning and end of the URI. When we hit `OK` on the dialog, nothing happened. 

Looking on the Chrome developer console, we saw that the response was a `400` from Leonardo. However, the UI didn't inform the user of the issue so it was very difficult to know what was going on.

**Comment by sharmatime** [comment]
I talked to Ilyana about this - there is only one workshop left on FireCloud so maybe not an important fix for FireCloud but if the same issue is occurring on Terra, we should definitely fix that. @zarsky-broad do you know if there are any UI warnings if you pass a cluster start up script URI that is broken?
