### ISSUE TITLE
Have workspace bucket name available via an environment variable

### ISSUE THREAD

**Issue by deflaux** [DataBiosphere/leonardo#704]
This will allow us to programmatically write files such as images to the workspace bucket and then view them using Terra's data tab.

**Comment by rtitle** [comment]
Good idea

**Comment by mbookman** [comment]
+1

**Comment by sharmatime** [comment]
Could be a number of approaches, so needs a tech doc

Bucket has long ID
Clusters are per project, but buckets are per workspace
Within a notebook you know what workspace you're in
Maybe when the workspace localizes the notebook to the cluster,

**Comment by bradtaylor** [comment]
It would also be good to have the workspace name itself there, because you can use that to get other attributes (like the bucket) with FISS if working in python. Could the Terra team run an extension that sets this variable?

**Comment by rtitle** [comment]
One idea is for Terra to localize an `.env` file to the workspace directory on the cluster when it localizes the notebooks. Then users would be able to read this `.env` file in code to access workspace-specific variables.

Another idea I've been toying with: what if Terra workspaces by default included a "skeleton" notebook which sets up the environment, and maybe includes documentation about how to get started with things like FISS, Hail, BigQuery, etc. That might be a nice experience for users.

**Comment by mbookman** [comment]
In https://github.com/DataBiosphere/saturn-ui/issues/1039 I noted that if we can get the workspace name, then we can get everything else about the workspace through API calls. The 1-1 mapping of workspace and bucket seems both durable and useful, so including that as well in the same manner as the workspace name would certainly be nice.

My one question is - if there were a `.env` file, how would I reliably access it from a notebook? Is there a environment variable, path, or function which would give me that? In thinking about workoing around https://github.com/DataBiosphere/saturn-ui/issues/1039, one option was to have a notebook figure out from either the current working directory or the notebook file's directory what the path was and then extract the workspace name. But this seemed unreliable and I'm concerned that dropping down a `.env` file without additional support is just the same problem.

**Comment by rtitle** [comment]
Still testing, but here's an early PR for this: https://github.com/DataBiosphere/leonardo/pull/841

This should provide `WORKSPACE_NAMESPACE`, `WORKSPACE_NAME`, and `WORKSPACE_BUCKET` EVs in a notebook (python and R kernels).

**Comment by rtitle** [comment]
This is merged to dev; it should release on 4/9. This provides `WORKSPACE_NAMESPACE`, `WORKSPACE_NAME`, and `WORKSPACE_BUCKET` EVs in python and R kernels. A cluster rebuild will be required.

**Comment by rtitle** [comment]
This was deployed on 4/11 (module https://github.com/databiosphere/leonardo/issues/864 which will be in the next release).

**Comment by mbookman** [comment]
Thanks @rtitle!

What is the cadence of "next release"? Is that expected to be tomorrow?

**Comment by rtitle** [comment]
We usually tag on Friday and release on Tuesday, so this is expected Tue 4/23. I will post & close this when it is in prod.
