### ISSUE TITLE
Update Leo on call playbook with changes from horizontal scaling

### ISSUE THREAD

**Issue by vkumra-broad** [DataBiosphere/leonardo#731]
Update the on call playbook to incorporate all the changes from horizontal scaling 

https://docs.google.com/document/d/1n0KZuHFE7nb9OJsmT2YLger7w2yE3Zy3R_fsC-zNrUk/edit#

**Comment by MatthewBemis** [comment]
Closed. This was partially done already. I have gone in and added a few more details.
