### ISSUE TITLE
Frequent Errors in Terra: "error auto creating clusters"

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#734]
This came up in a demo that @abaumann was giving for AnVIL.

I believe Terra eagerly tries to create clusters in every project the user is a member of. For whatever reason, many projects (especially older ones) don't have dataproc enabled. The failure mode is a 503 returned from Leo, and an orange pop-up in Terra: "Error auto-creating clusters". We should fix this experience. Some options:

1. Make Terra not be so eager. For example @abaumann is in 80 billing projects -- does he really need a cluster in each one?
2. Make Leo handle errors more gracefully -- instead of returning 503 return some more descriptive error message which the UI could handle.
3. Make Leo automatically enable Dataproc in projects where it's not enabled, and then create a cluster in that project as requested.

cc @sharmatime @bradtaylor

**Comment by rtitle** [comment]
Maybe a combination of 1 and 3 is the right solution here.
- Make Terra more "smartly eager" -- e.g. only create a cluster in recently used projects (not sure the exact algorithm)
- Make Leo auto-enable Dataproc were it's not enabled so it can fulfill user requests

**Comment by sharmatime** [comment]
Talked to @bradtaylor about this. Terra plans to disable auto creation of clusters in old projects so this error doesn't show unless people actually enter the old project.

**Comment by sharmatime** [comment]
@MatthewBemis , @rtitle since Terra made cluster creation manual I feel like this ticket is no longer as high priority as it used to be?

**Comment by rtitle** [comment]
Yeah, that's my view: this ticket is lower priority now that Terra doesn't auto create clusters
