### ISSUE TITLE
Instances with local SSDs can't be stopped

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#735]
There is a cluster `broad-firecloud-dsde/ltl-tutorial` which has been in `Stopping` state for some time. The master is stopped but the 2 workers are still running. When I logged into the cloud console I saw:
```
You cannot stop an instance that uses a local SSD
```
This seems to be a gap in Leo functionality: you can create a cluster with local SSDs but not stop it.

**Comment by sharmatime** [comment]
We should kill the rogue cluster and prevent it from happening to users by taking this option out of the API for now. In the future if we hear a request for it, and we can see how it benefits multiple users we can put it back

**Comment by rtitle** [comment]
I manually killed the rogule `broad-firecloud-dsde/ltl-tutorial` cluster
