### ISSUE TITLE
Develop a process for updating libraries and packages in docker image

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#740]
Today we have libraries and packages pegged in the Docker image, and this prevents automatic updates from occurring that can break dependencies inside the docker image, or in users code. 

We should have a process for making decisions on what minor version changes we will update in the image, and what things we think will cause breaking changes and won't update. 

For example, we should be updating Hail 0.2 on a regular frequency (~1 per month). Along with our Hail update we can evaluate what other updates we should do. 

Eventually we can think about how to automate this process

cc @rtitle, @vkumra-broad

**Comment by MatthewBemis** [comment]
@sharmatime to add to reproducibility epic when there is one
