### ISSUE TITLE
Spike: Evaluate next steps for performance testing our horizontal scaling implementation

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#741]
With the NHS workshop scalability issues we want to performance test the horizontal scaling changes  in order to identify potential bottle necks/ risk a head of future workshops, user growth.

In order to understand how to improve our current performance tests a number of things need to be done:

1. Review Kaan's performance testing doc and Epic
2. Understand what our current performance test suite measures
3. Understand the gaps between what our current tests measure, and reality (e.g. how could we have known that we'd have a problem with the NHS workshop)
4. Iterate on Kaan's work if required
5. Propose next steps in a tech doc (this might just be iterating on Kaan's tech doc)
6. Get tech doc reviewed
7. Break down work into tickets (this might be just iterating on Kaan's tickets)

@rtitle, @vkumra-broad

**Comment by MatthewBemis** [comment]
Closed in favor of new Perf Testing epic
