### ISSUE TITLE
JupyterLab Extension From Single File

### ISSUE THREAD

**Issue by blrubenstein** [DataBiosphere/leonardo#742]
Currently, JupyterLab extensions require a full tarball with all the NPM package setup boilerplate, and that should probably live in Leo so that every app doesn't have to maintain the same boilerplate folder template.

**Comment by blrubenstein** [comment]
This is the template, only the index file should be required, it should be copied and replaced. The template should be saved onto the Leo image.

https://github.com/jupyterlab/extension-cookiecutter-ts

**Comment by rtitle** [comment]
While this feature makes sense, I didn't see it as a requirement for the original work. We made the choice for Leo to support JL extensions in the same format as JL itself: e.g. a public npm package or a tarball of an npm package. See: https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#installing-extensions. In other words, Leo is just a pass-through to JupyterLab, and we give callers full control over their extension code.

Is it a problem for AoU or Terra to host a fully packaged extension tarball? Again, `extension-cookiecutter-ts` seems like a nice feature to add, I just don't understand why it's a blocker. Thanks

**Comment by blrubenstein** [comment]
I don't think it is actually a blocker... I will remove those. I do know the Terra devs are making a choice to block their development work on this feature, because a packaged tarball can't actually sit in source control cleanly. I think it would be possible to host the structure in GCS, and just upload the typescript/javascript file on its own to that file structure. I will play around with that myself tomorrow probably, but defer to @zarsky-broad for the Terra perspective, because I know he has done a lot more research into this.

**Comment by rtitle** [comment]
Would a potential architecture be for Terra/AoU to build and package their npm packages as part of their CI/CD pipeline, and pass an artifactory URL to Leo? (Or alternatively, publish the extension to npm?) I'm a little hesitant to make assumptions in Leo about extension package structure, etc. It might be beneficial for apps to have full control over their extension code & build process, instead of splitting logic between apps and Leo. Happy to talk with faces tomorrow.

**Comment by blrubenstein** [comment]
Yeah, lets grab some face time today.

**Comment by rtitle** [comment]
Deployed on 2/27/19
