### ISSUE TITLE
Spike: Need to be able to re-fuse the Docker volume to a different bucket if the user changes workspaces 

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#756]
Options:
1. Leo SSH into VM
2. Web service call 
3. Recreate cluster in each new workspace (slow)
4. User has different cluster in each workspace ($$$)

Outcome is a tech doc outlining a solution

**Comment by vkumra-broad** [comment]
https://docs.google.com/document/d/1jzW3UqS5ZsodBGXZca7TOlrFBdwnI07qWhLdbzHDMGo/edit
