### ISSUE TITLE
Spike: How do other implementations of RStudio maintain their state over time?

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#757]
In RStudio Cloud, and RStudio server, when a user returns to their session in RStudio it is automatically fully restored. There must be a feature that enables session persistence. We need to understand how that works. We also should think about how to track the current RStudio session, in case the user starts a fresh RStudio session in the workspace.

The outcome of this spike is a tech doc on how to implement most recent session restore in a workspace for a user

In addition to state, the user needs to be able to save and access these files at RStudio runtime:
https://docs.google.com/document/d/1xbG1X3wFIY0ZChuae7HQu4tA-S9xy5S6jqvq7w4EEpw/edit#

**Comment by rtitle** [comment]
Deployed to production
