### ISSUE TITLE
Spike: Evaluate GCS fuse performance, in addition to possible GCS fuse alternatives

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#763]
We've heard about a number of alternatives that were developed due to performance issues with GCS fuse. We should evaluate some of those alternatives relative to GCS fuse to make sure we're making good technology choices in the short term that open doors instead of close them (e.g. using fuse to localize large data files for analysis). 

Possible alternatives to evaluate in tandem with GCS fuse:
- https://github.com/mitre/fusera

We can evaluate the performance in several areas:
- Repeated (rapid) writes back to the bucket (for example, if an RStudio session is auto-saving)
- Listing many files at once (what’s typical?)
- Delocalizing large files
- Localizing large files
- Information about how gcsfuse caches can be found here.
- Ask Brad for examples of the types of data files that people might want try to localize for analysis
- Ask Megan Shand, or Nicole Deflaux for large RStudio projects to load

Outcomes:
 - Time box this research to 2 days
 - Tech doc reviewing the performance of the tools
 - We have data that helps us make a decision on which tool to use
 - We make a decision on fusing the entire workspace bucket to the VM, or only fusing the users workspace folder

**Comment by sharmatime** [comment]
@bradtaylor can you point us at the GCS fuse alternative you mentioned in the skateboard doc from Phil Montgomery?

**Comment by rtitle** [comment]
Bernick says we should check out fusera

**Comment by akarukappadath** [comment]
I spoke to Phil Montgomery about puFS, and it seems like the ways in which puFS is superior to GCSfuse are not relevant to our use cases for Leo. Fusera seems to have a use case specific to SRA data only. It looks like GCSfuse will be our best option.
