### ISSUE TITLE
Token refresh not working from JupyterLab

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#770]
See ZenDesk ticket from Nicole: https://broadinstitute.zendesk.com/agent/tickets/970

I suspect the front-end token refresh which runs as a Jupyter extension is not running lab, causing users' tokens to expire and see 401 errors. We should resolve this, either by:

- providing the same code/functionality as a labextension
- having Terra UI call /setCookie periodically in the background

**Comment by schaluva** [comment]
Nicole also reached out to mention that she experiences the 401 errors when actively using JupyterLab (not just after leaving the computer for a while).

**Comment by mbookman** [comment]
Cross-linking with the saturn-ui issue: https://github.com/DataBiosphere/saturn-ui/issues/1116
Presumably this is the same issue. I'm unclear whether it is a Leonardo issue or Terra.

**Comment by rtitle** [comment]
@mbookman yes I think this is the same Leo issue. We're hoping to have a fix out next week.

In the meantime an (unforunate) workaround is to have a Terra notebook (not lab) open in a different tab while you use Lab.

**Comment by mbookman** [comment]
Thanks! That's a simple workaround to use for now.
Probably also explains why I would see this intermittently, as I often have this very setup going for other reasons.

**Comment by rtitle** [comment]
Update: we have a fix for this and are targetting a release next week (Tue).

**Comment by rtitle** [comment]
This fix is deployed to production as of 2/27/19 5pm. However note you will need to rebuild your cluster in order to obtain the fix.
