### ISSUE TITLE
Clusters with only RStudio on them get stuck in Starting status

### ISSUE THREAD

**Issue by vkumra-broad** [DataBiosphere/leonardo#771]
Cluster start code hits the jupyter api to check if jupyter is actually running before updating the status from `Starting` to `Running`. A cluster with only RStudio installed fails this test and is hence stuck in `Starting` status. Interestingly, even though the cluster is in `Starting` status you can access RStudio on it since the dataproc & dockers are running correctly, just the status is wrong.

**Comment by vkumra-broad** [comment]
https://github.com/DataBiosphere/leonardo/blob/91d65491beb96b4ff4678c56ad0989a85f675739/src/main/scala/org/broadinstitute/dsde/workbench/leonardo/monitor/ClusterMonitorActor.scala#L297

**Comment by sharmatime** [comment]
Looks like RStudio has an API package. If you're inside RStudio console you can run:

help(package = "rstudioapi")

And see the API calls associated with the RStudio API package. Maybe this is a possible lead into a solution.
