### ISSUE TITLE
RStudio Server Pro Docker Container

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#785]
Create a docker image that includes RStudio Server Pro, instead of the open source version

Bulk of the work is make a Dockerfile with RStudio Pro
Incorporate installation instructions into the Docker
Make a new repo for this container so it's not coupled to the Leo build (nice to have)

**Comment by MatthewBemis** [comment]
See https://github.com/mobilizingcs/rstudio-server-pro for a potential reference

**Comment by sharmatime** [comment]
Can download RStudio sever pro here: https://www.rstudio.com/products/rstudio/download-commercial/
