### ISSUE TITLE
Run ASHG performance tests with 300 users

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#796]
Our user growth goals for BVDP year 2 300 engaged users per month. In addition to these goals, we will hold frequent workshops that can range from 20-60 simultaneous users. With these goals in mind, engineering set a target for Terra to support 300 simultaneous users. Prior to our Horizontal Scaling work, we could already support 200 simultaneous users as measured by our ASHG tests. 

Until we have capacity to do our performance testing epic (, https://github.com/DataBiosphere/leonardo/issues/680), in the short term we should run our ASHG performance tests with 300 simultaneous users.

**Comment by MatthewBemis** [comment]
Closed in favor of new perf testing epic
