### ISSUE TITLE
Spike: Notebooks stay associated with the appropriate image

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#807]
Problem:
 - Updates to libraries and packages loaded with notebooks can break dependencies in a users notebook
 - In order to reproduce analyses, the code needs to be associated with the runtime compute

What is the resulting user experience?
 - Analyses currently being developed on aren’t broken due to image updates
 - Users and their collaborators can go back to old analyses and replicate them without encountering broken dependencies or modified results due to image updates
 - Cluster updates do not change the packages, libraries, versions on an image on a user’s cluster
 - User can create a new notebook with an older image version

See epic document for more context:
https://docs.google.com/document/d/1dVzSFnvI0RSB3GJAs6K_60MLpk83plzMiQTZkBYO78I/edit#

**Comment by akarukappadath** [comment]
Summary: For Jupyter notebooks, it looks like the most straightforward thing to do would be to save the image tag in the metadata of the notebook. This should be able to be set through an API call (see https://jupyter-notebook.readthedocs.io/en/stable/extending/contents.html). Then, when the notebook is being opened, we can check to make sure that the cluster being used contains the same image as the one that is saved into the notebook metadata. This would also involve supporting user-specified docker images and UI changes to notify users of the image change. It would also be a good idea to separate the docker image build and push process, probably by creating its own github repo.
