### ISSUE TITLE
Spike: Support IGV.js in Terra

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#808]
What problem is it solving? 
 - Researchers need to manually check the quality of variants identified as important from their sequenced samples.

What does done look like? 
 - IGV.js is embedded in the browser in Terra
 - What is the resulting user experience?
 - A more seamless ux, where users can manually inspect variants from files directly in their workspace
 - Users need to be able to open IGV, select workspace data to load and examine

Technical info:
 - Use igv.js (https://github.com/igvteam/igv.js#igvjs) to embed an interactive genome visualization component in your web app.
 - Example of web app [here](https://igv.org/app/)

**Comment by sharmatime** [comment]
Meeting with Vicky and Eric next week to understand the work involved

**Comment by MatthewBemis** [comment]
Closing because another team is taking care of this work
