### ISSUE TITLE
Cannot use sunburstR package in Leo

### ISSUE THREAD

**Issue by blrubenstein** [DataBiosphere/leonardo#815]
A user in All of Us tried to use the sunburstR package in Leo, and found that they couldn't. They hypothesized that it may be that sunburstR tries to access the page native JS and open a new tab with the chart.

https://cran.r-project.org/web/packages/sunburstR/vignettes/sunburst-2-0-0.html

From the user:
```
This a link for a sequence file you can use to try it:
https://raw.githubusercontent.com/timelyportfolio/sunburstR/master/inst/examples/visit-sequences.csv
To run it all you need to do is:
library(sunburstR)
sequences <- read.csv(
 "visit-sequences.csv"
 ,header=F
 ,stringsAsFactors = FALSE
)
sunburst(sequences)
To install the package: install.packages("sunburstR")
```

This has not been tested in regular jupyter yet.

**Comment by sharmatime** [comment]
Lina said she tired in in Jupyter and it doesn't work. I suggested she file an issue on the Sunburst package github to see if there is some trickery that is required to make it work in Jupyter
