### ISSUE TITLE
JupyterLab list of workspace notebooks does not reflect updates by others

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#818]
Problem from Nicole:

Use two different Google Accounts, A and B.
 - use account A in Saturn UI to make a new Jupyter notebook foo.ipynb and add a cell saying 'hello from A!'
 - pause A's cluster 
 - use account B to open foo.ipynb and add another cell saying 'hello from B!', leave this running
 - start A's cluster
 - use account A to 'open in JupyterLab' some other notebook
 - Then, in JupyterLab (not the Saturn UI), navigate your filesystem to open foo.ipynb <---- there is no cell from step 3.

 A and B both have the notebook open, they are both working away adding new cells, and they do not realize they are diverging. I've had it in this state now for 10 minutes and haven't yet gotten any warnings about edited recently or you are about to overwrite yes/no? Someone at some point will 'win' and the other person will loose work, maybe a lot of work.

Related to this issue is https://github.com/databiosphere/saturn-ui/issues/1206:
 - New notebooks are added to a workspace and not reflected in the JupyterLab file tree

cc @deflaux

**Comment by MatthewBemis** [comment]
Closing in favor of rewriting a new epic ticket to cover the work that will be done this Q
