### ISSUE TITLE
Spike: Collaboration in Notebooks

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#825]
Inside a notebook display info about who currently has the notebook open

Problem: 
 - Users want to collaborate on the same notebook, but there is no safe way to do it since users can overwrite each other’s changes.
 - Even more important now that JupyterLab filetree list of workspace notebooks does not reflect updates by others

**Anecdotes:**
 - For Nurses' Health Study, we are collectively working on the smoking and lung cancer notebook. We email each other to take turns editing it.
 - But for Nurses' people still get worried and now we find ourselves with an old master copy 'Smoking and Lung Cancer.ipynb' and the new master copy 'MASTER Smoking and Lung Cancer.ipynb'.

Implementation notes:
 - Leo has this information already, so it could be implemented as a Leo endpoint
 - Could be displayed via front-end extension or in the app UI (or both)
 - Display the user’s email address
 - Needs some investigation on how to achieve this for Rstudio, as it currently relies on health checks from a Jupyter UI extension.
Pros:
 - Should be low cost on both backend and UI
Cons
 - Doesn’t prevent actual

**Comment by MatthewBemis** [comment]
Closing in favor of new epic being created for this Q's work
