### ISSUE TITLE
"Permission denied" attempting to install JupyterLab extension

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/leonardo#831]
This had been working on a previous notebook VM, but I rebuilt and can no longer install the JupyterLab table of contents extension:

```
$ jupyter labextension install @jupyterlab/toc
Node v10.15.1

> /usr/bin/npm pack @jupyterlab/toc
npm WARN npm npm does not support Node.js v10.15.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
jupyterlab-toc-0.6.0.tgz

Errored, use --debug for full output:
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter/lab/extensions/jupyterlab-toc-0.6.0.tgz'
```

Taking a look at the directory ownership in the `jupyter/lab` directory shows that the `extensions` directory is owned by root, rather than the jupyter user, and with no writability except by owner:

```
$ ls -l /usr/local/share/jupyter/lab/
total 24
drwxr-sr-x 2 root         users 4096 Mar 16 04:38 extensions
drwxr-sr-x 1 jupyter-user users 4096 Mar  9 01:09 schemas
drwxr-sr-x 2 root         users 4096 Mar 16 04:38 settings
drwxr-sr-x 6 root         users 4096 Mar 16 04:38 staging
drwxr-sr-x 2 root         users 4096 Mar 16 04:39 static
drwxr-sr-x 1 jupyter-user users 4096 Mar  9 01:09 themes
```

Should the ownership be changed or permissions be opened up? Should I be installing extensions elsewhere?

Thanks!

**Comment by sharmatime** [comment]
Thanks a lot Matt, we're actively looking into this

**Comment by rtitle** [comment]
The fix for this was deployed on 4/11.

**Comment by mbookman** [comment]
Can someone else confirm the fix for this is in production?
I deleted my cluster and recreated it and I get:

```
!jupyter labextension install @jupyterlab/toc

Node v10.15.2

> /usr/bin/npm pack @jupyterlab/toc
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
jupyterlab-toc-0.6.0.tgz info using node@v10.15.25.2

Errored, use --debug for full output:
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter/lab/extensions/jupyterlab-toc-0.6.0.tgz'
```

**Comment by rtitle** [comment]
Hi @mbookman, I started looking at this and noticed something odd. The commit with the fix went through our deploy process on 4/11, but the prior version is still running on the Leo production servers. So we're effectively still running the previous release. I'm following up on this...

**Comment by rtitle** [comment]
It was actually just 1 server that was not upgraded. I redeployed and recreated a cluster and this seems to work now:

![image](https://user-images.githubusercontent.com/5368863/56331196-50f92680-6159-11e9-9cc5-fb5c13c07088.png)

Sorry for the confusion here. I believe if you rebuild your cluster after 4/17 9:30pm EST it should work.

**Comment by rtitle** [comment]
Re-closing since this has been released.
