### ISSUE TITLE
Links in read-only mode are broken

### ISSUE THREAD

**Issue by melissachang** [DataBiosphere/leonardo#834]
- Navigate to [this notebook](https://app.terra.bio/#workspaces/fc-product-demo/Melissa%20Baseline%20Verily/notebooks/launch/R%20-%20Baseline%20small%20multiples%20data%20visualization.ipynb?read-only=true)
- Click on any link, such as the first one. I see:

![1](https://user-images.githubusercontent.com/10929390/54641809-49f2d180-4a50-11e9-991e-f4d5ce1cb50f.png)

I'm guessing this bug happens with any read-only notebook. So you can try with any notebook, since you don't have access to above notebook.

**Comment by rtitle** [comment]
I'm redirecting this to @bradtaylor and @panentheos, since that team owns the read-only notebooks service (calhoun).

However read-only mode seems to be working for me for several of my notebooks. For example: 
![image](https://user-images.githubusercontent.com/5368863/54642046-11f88800-4a6a-11e9-8e16-30870bcff619.png)

I wonder if it's something specific to your notebook. If you open the browser console, do any errors appear in there?

**Comment by melissachang** [comment]
Only links are broken. Can you make a link and try clicking on it? Clicking will work on normal mode, but not read-only mode.

Eg `[google](https://google.com)`

**Comment by rtitle** [comment]
[testing](https://app.terra.bio/#workspaces/broad-firecloud-dsde/Demo_2017-10-24/notebooks/launch/gatk-CNN-python%20(1).ipynb/?read-only=true)

**Comment by rtitle** [comment]
I still wonder if it's an issue with the notebook itself. The read only view doesn't go through Leo/Jupyter, but to a separate service which is essentially calling `nbconvert` on the notebook. There may be something going on in there. Perhaps someone from @bradtaylor's team can check the calhoun server logs for clues. Also do any errors appear in the browser console?

**Comment by melissachang** [comment]
Oops yeah, I do see an error in the console:
```
Refused to display 'https://tableau.verilystudies.com/#/site/VerilyScience/views/BaselineCompBioExploration/AssayvAssaybyDisease?:iid=1' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

**Comment by rtitle** [comment]
Huh, so maybe it's trying to follow that link when converting the notebook to HTML, and failing to display it inside a frame.

**Comment by panentheos** [comment]
I think we can make this work by splicing a `base` element into the preview iframe so any links would open in the parent window. I'll create a ticket in our repo to investigate this solution. (Feel free to close this one if you want)
