### ISSUE TITLE
Install GATK and Samtools by default

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/leonardo#839]
These are basic command line programs for exploring and analyzing variant and read data respectively. To make our notebooks and terminals useful to geneticists, these foundational tools should be present in the leo image by default.
Terra communications is giving tutorials on GATK in notebooks and they have to jump through hoops to get users working on this.
@sharmatime

**Comment by rtitle** [comment]
This was deployed on 5/1!
