### ISSUE TITLE
Consider allowing root usage in notebooks

### ISSUE THREAD

**Issue by calbach** [DataBiosphere/leonardo#840]
e.g. allowing execution of cells like:

```
! sudo apt-get update
! sudo apt-get install my-package
```

(alternatively, already logged in as the root user)

This would allow us to have quick (no cluster restart) workarounds for issues like https://github.com/DataBiosphere/leonardo/issues/813 and https://github.com/DataBiosphere/leonardo/issues/839

We should investigate what tradeoffs exist (if any) by allowing the user this privilege.

**Comment by MatthewBemis** [comment]
just spoke with @adrazhi about this. from a security perspective, this shouldn't be an issue. we will see if any gov't documentation needs to be updated as a result.

ETA is still TBD as there are higher priorities but we should be good to move forward with this

**Comment by briandoconnor** [comment]
+1 for this, I'm stuck right now running a notebook with an external dependency.  I can't apt-get install so I can't run this notebook.
