### ISSUE TITLE
Resize compute without rebuilding cluster from scratch (Expand PATCH endpoint)

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#842]
Note: Rob's finished the backend component of this story. The front end component is being tracked in #885 

Current state:
 - Geetha is running an analysis and she needs more CPUs/memory/Disk space on her VM. She clicks on the "Custom" drop down in the Terra compute runtime UI, and selects more CPUs/memory/Disk, then clicks update
-Update triggers a complete cluster rebuild, which takes 5-10 minutes. 

Desired user outcome:
 - Resizing compute does not trigger a complete cluster rebuild, but instead triggers a stop/start, which will allow Geetha to access her compute much faster

Additional context: Expand cluster PATCH endpoint to include changing VM settings and enable the Terra UI to call it
 - CPUs
 - Mem 
 - Disk
 - Autopause
 - Number of cluster nodes if Spark
 - Change all these by calling the PATCH endpoint, which triggers a stop/start, which will take time but won’t require a complete rebuild
 - Little bit of UI work to call the patch, and Leo work to do support CPU, Mem, disk. Current PATCH just has autopause and number of nodes in Spark cluster

**Comment by rtitle** [comment]
This is in production as of 4/24.
