### ISSUE TITLE
Google docs style comments in JupyterLab

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#856]
Current state: When I'm reviewing a collaborators JupyterLab notebook inside a workspace, I have to email them with specific comments on their code. This is painful because I have to leave the notebook, and copy and paste code into email.

Desired user outcome: I can leave comments directly on code inside of a JupyterLab notebook. 

Scope:
 -  This ticket assumes that a [commenting extension](https://github.com/jupyterlab/jupyterlab-commenting) in JupyterLab already exists (might not be ready for primetime though) - needs evaluation
 -  Email notifications for comments are out of scope for now

**Comment by vkumra-broad** [comment]
The commenting extension listed has not been released (https://github.com/jupyterlab/jupyterlab-commenting/issues/16)

There is a  [demo](https://github.com/jupytercalpoly/rich-context-demo) that we should checkout the to make sure that this extension fits our requirements.
