### ISSUE TITLE
Compute runtime autodelete UI

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#860]
See: https://github.com/DataBiosphere/leonardo/pull/848

Current state:
 - After a user finishes working on a cluster, they may forget to come back and delete it
 - Forgetting to delete a cluster can cost $87/year or $1.68/week

Desired user outcome:
 - When a user creates a cluster, they can set auto delete of that cluster to occur after a specified time of inactivity
 - After a user creates a cluster, they can also set the auto delete interval for the cluster

Acceptance criteria:
 - In the compute runtime UI there should be an option for selecting auto delete and setting the time interval during the following times: At cluster creation time, while the cluster is paused, and when the cluster is running
 -  When the user sets an auto delete interval it actually deletes after inactivity for that time period

**Comment by mbookman** [comment]
Related to this (not sure if it deserves a separate issue):

- I am a Terra Billing Project Administrator.
- I remove someone from my Billing Project

I assume that the user's notebook is not automatically deleted.
Will it ever be cleaned up?
Does a Billing Admin have any ability to know whose notebook VMs and disks belong to whom?

Thanks!

**Comment by sharmatime** [comment]
@mbookman the notebook(s) and the cluster is not deleted. I'm not sure if the billing admin also has project owner permissions. If they do, they could probably hit the Leo API to see what clusters were associated with that billing project and delete them. I think the expected behavior should be for clusters to be deleted and notebooks to remain?

@rtitle, @MatthewBemis do any of you know if billing project admin has project owner permissions? Does this seem right? Anything to add?

**Comment by MatthewBemis** [comment]
@sharmatime Terra billing project owners only have the project viewer role on the underlying Google project. They can see which VMs exist in their project but I'm not sure if there's enough info in there to easily determine which VMs/disks belong to whom. Viewer certainly isn't enough power to _delete_ those resources.

Paths forward:

* Big lift: Allow Terra billing project owners to delete clusters spun up in their project. This would be similar to how Terra billing project owners can delete workspaces that they have not explicitly been added to.
* Light lift: Add a label to the VMs so Terra billing project owners can know who the resource belongs to.
