### ISSUE TITLE
WORKSPACE_NAME environment variable is empty when workspace name has spaces

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/leonardo#864]
I recreated my cluster post 4/9/2019.
I was looking to pick up #841 .

I opened a notebook and added a new cell:

```
%%bash
env | grep WORKSPACE
```
```
WORKSPACE_NAME=
WORKSPACE_NAMESPACE=fc-<correct>
WORKSPACE_BUCKET=gs://fc-secure-<correct>
```

I opened a different notebook in a workspace that does not have a space in the name and it worked fine.

Taking a quick pass over #841, I think that this line:

`export WORKSPACE_NAME="$(basename $PWD)"
`

needs to be:

`export WORKSPACE_NAME="$(basename "$PWD")"`

**Comment by mbookman** [comment]
Confirmed from the command line.

```
$ PWD="$(pwd)"
$ echo $PWD
/home/jupyter-user/my - workspace - with spaces

$ basename $PWD
basename: extra operand ‘workspace’
Try 'basename --help' for more information.

$ basename "$PWD"
my - workspace - with spaces
```

**Comment by rtitle** [comment]
Doh! Thanks for the catch and suggested fix. Will make that change.

**Comment by rtitle** [comment]
Merged fix to dev.

**Comment by mbookman** [comment]
I recreated my cluster today and confirmed that WORKSPACE_NAME variable was set correctly for a notebook whose workspace name has a space in it.

Thanks!

**Comment by rtitle** [comment]
Confirmed, this fix is in production. Closing.
