### ISSUE TITLE
Handle cluster creation if current zone doesn't have enough resources

### ISSUE THREAD

**Issue by vkumra-broad** [DataBiosphere/leonardo#870]
Automation tests failed because the zone did not have enough resources.

One way to handle this would be to  build retries in the cluster creation code.

From Automation tests:

```
The zone 'projects/gpalloc-qa-master-0a2klzz/zones/us-central1-c' does not have enough resources available to fulfill the request.  '(resource type:compute)'.
```

**Comment by MatthewBemis** [comment]
We should also open a ticket with Google about this. It seems odd that we let Dataproc pick the region but then it is picking a region that doesn't have any resources available.

**Comment by Qi77Qi** [comment]
1. add zone field when creating dataproc cluster, and expose the field in api.

1. update automation test to maybe round robin a set of zones instead of always using the default one

**Comment by Qi77Qi** [comment]
Google customer support said they've rolled out a fix. Think we can close this one and reopen if the issue persists?

**Comment by Qi77Qi** [comment]
I'm going to close this issue for now, and we can reopen if tests fail for the same reason
