### ISSUE TITLE
Slow notebook performance issues

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/leonardo#879]
Last Wednesday, April 17th around 5pm there were reports of slow notebook loads:

Reported by @abaumann:

"Yesterday during the demo notebooks was having issues. It was very hit or miss - once a read-only preview worked, but cluster creation was slow, then a cluster came up quickly, but they switched to another notebook and it hung, so it was all over the place"

Could we look into our logs to see if there were any obvious problems then?

**Comment by jdcanas** [comment]
should be faster now
